# Generated by Django 5.2.9 on 2025-12-17 14:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductManufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("website", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="manufacturers/"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "manufacturer",
                "verbose_name_plural": "manufacturers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.productcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "product category",
                "verbose_name_plural": "product categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_number",
                    models.CharField(
                        db_index=True,
                        help_text="Internal part number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "manufacturer_part_number",
                    models.CharField(
                        db_index=True,
                        help_text="Manufacturer part number",
                        max_length=100,
                    ),
                ),
                (
                    "upc",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Universal Product Code",
                        max_length=20,
                    ),
                ),
                (
                    "ean",
                    models.CharField(
                        blank=True, help_text="European Article Number", max_length=20
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=500, unique=True)),
                ("description", models.TextField(blank=True)),
                ("long_description", models.TextField(blank=True)),
                (
                    "assembled_in",
                    django_countries.fields.CountryField(
                        blank=True,
                        help_text="Country where final assembly occurs",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DISCONTINUED", "Discontinued"),
                            ("PENDING", "Pending"),
                            ("OUT_OF_STOCK", "Out of Stock"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Base retail price", max_digits=10
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("quantity_in_stock", models.IntegerField(default=0)),
                ("minimum_order_quantity", models.IntegerField(default=1)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in pounds",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Length in inches",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Width in inches",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in inches",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.productcategory",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.productmanufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductCountryOfOrigin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary Origin"),
                            ("SECONDARY", "Secondary Origin"),
                            ("COMPONENT", "Component Origin"),
                        ],
                        default="COMPONENT",
                        max_length=20,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        help_text="Lower numbers appear first"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_origins",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Installation Manual"),
                            ("SPEC_SHEET", "Specification Sheet"),
                            ("WARRANTY", "Warranty Information"),
                            ("DIAGRAM", "Technical Diagram"),
                            ("CERTIFICATE", "Certificate"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="product_documents/%Y/%m/")),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("is_public", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product document",
                "verbose_name_plural": "product documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/%Y/%m/")),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary"),
                            ("ALTERNATE", "Alternate View"),
                            ("DETAIL", "Detail"),
                            ("LIFESTYLE", "Lifestyle"),
                            ("DIAGRAM", "Diagram"),
                            ("INSTALLATION", "Installation"),
                        ],
                        db_index=True,
                        default="ALTERNATE",
                        max_length=20,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("caption", models.CharField(blank=True, max_length=500)),
                ("display_order", models.IntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product image",
                "verbose_name_plural": "product images",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("ACCESSORY", "Accessory"),
                            ("REPLACEMENT", "Replacement"),
                            ("UPGRADE", "Upgrade"),
                            ("RELATED", "Related Product"),
                            ("BUNDLE", "Bundle"),
                            ("ALTERNATIVE", "Alternative"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_products",
                        to="products.product",
                    ),
                ),
                (
                    "related_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_to",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product relationship",
                "verbose_name_plural": "product relationships",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(blank=True, db_index=True, max_length=50)),
                (
                    "material",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("finish", models.CharField(blank=True, max_length=100)),
                ("torque_rating", models.CharField(blank=True, max_length=50)),
                ("horsepower_rating", models.CharField(blank=True, max_length=50)),
                ("voltage", models.CharField(blank=True, max_length=20)),
                ("amperage", models.CharField(blank=True, max_length=20)),
                ("thread_size", models.CharField(blank=True, max_length=50)),
                ("diameter", models.CharField(blank=True, max_length=50)),
                ("bore_size", models.CharField(blank=True, max_length=50)),
                (
                    "fitment_type",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("placement", models.CharField(blank=True, max_length=100)),
                ("warranty_period", models.CharField(blank=True, max_length=100)),
                ("certifications", models.TextField(blank=True)),
                ("country_of_origin", models.CharField(blank=True, max_length=100)),
                ("pieces_per_package", models.IntegerField(blank=True, null=True)),
                ("package_type", models.CharField(blank=True, max_length=100)),
                (
                    "custom_field_1",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "custom_field_2",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "custom_field_3",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("custom_field_4", models.TextField(blank=True)),
                ("custom_field_5", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product attribute",
                "verbose_name_plural": "product attributes",
                "indexes": [
                    models.Index(fields=["color"], name="products_pr_color_c6bfd0_idx"),
                    models.Index(
                        fields=["material"], name="products_pr_materia_c93cff_idx"
                    ),
                    models.Index(
                        fields=["fitment_type"], name="products_pr_fitment_77243c_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(
                fields=["parent", "is_active"], name="products_pr_parent__d76081_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productcountryoforigin",
            unique_together={("product", "country", "role")},
        ),
        migrations.AddIndex(
            model_name="productdocument",
            index=models.Index(
                fields=["product", "document_type"],
                name="products_pr_product_990cc7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "image_type", "is_active"],
                name="products_pr_product_c96f9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["display_order"], name="products_pr_display_5b8ce6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["part_number"], name="products_pr_part_nu_e5d5be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["manufacturer_part_number"],
                name="products_pr_manufac_1a2251_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="products_pr_categor_50f5f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["manufacturer", "is_active"],
                name="products_pr_manufac_229295_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "is_active"], name="products_pr_status_c4a457_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "is_active"],
                name="products_pr_is_feat_a1ecf6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="products_pr_search__98d711_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="productrelationship",
            index=models.Index(
                fields=["product", "relationship_type"],
                name="products_pr_product_be6089_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productrelationship",
            unique_together={("product", "related_product", "relationship_type")},
        ),
    ]
