# Generated by Django 5.2.9 on 2025-12-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in inches",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Length in inches",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Width in inches",
                max_digits=10,
                null=True,
            ),
        ),
    ]
