# Generated by Django 5.2.9 on 2025-12-29 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("REQUIRED", "Required Field"),
                            ("FORMAT", "Format Validation"),
                            ("RANGE", "Range Validation"),
                            ("REFERENCE", "Reference Check"),
                            ("CUSTOM", "Custom Logic"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("field_name", models.CharField(db_index=True, max_length=100)),
                (
                    "validation_expression",
                    models.TextField(
                        help_text="Regex or Python expression for validation"
                    ),
                ),
                ("error_message", models.CharField(max_length=500)),
                ("can_autocorrect", models.BooleanField(default=False)),
                (
                    "correction_logic",
                    models.TextField(
                        blank=True, help_text="Python code for auto-correction"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "validation rule",
                "verbose_name_plural": "validation rules",
                "ordering": ["field_name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ValidationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(upload_to="validation_uploads/%Y/%m/%d/"),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("processed_rows", models.IntegerField(default=0)),
                ("valid_rows", models.IntegerField(default=0)),
                ("invalid_rows", models.IntegerField(default=0)),
                ("corrected_rows", models.IntegerField(default=0)),
                (
                    "validated_file",
                    models.FileField(
                        blank=True, null=True, upload_to="validation_results/%Y/%m/%d/"
                    ),
                ),
                (
                    "error_report",
                    models.FileField(
                        blank=True, null=True, upload_to="validation_reports/%Y/%m/%d/"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "validation job",
                "verbose_name_plural": "validation jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField(db_index=True)),
                ("column_name", models.CharField(blank=True, max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("ERROR", "Error"),
                            ("WARNING", "Warning"),
                            ("INFO", "Info"),
                        ],
                        db_index=True,
                        default="ERROR",
                        max_length=20,
                    ),
                ),
                ("error_code", models.CharField(db_index=True, max_length=50)),
                ("error_message", models.TextField()),
                ("original_value", models.TextField(blank=True)),
                ("suggested_value", models.TextField(blank=True)),
                ("was_corrected", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "validation_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="validator.validationjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "validation error",
                "verbose_name_plural": "validation errors",
                "ordering": ["row_number"],
            },
        ),
        migrations.AddIndex(
            model_name="validationjob",
            index=models.Index(
                fields=["user", "status"], name="validator_v_user_id_dcac72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationjob",
            index=models.Index(
                fields=["status", "created_at"], name="validator_v_status_9ed347_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationerror",
            index=models.Index(
                fields=["validation_job", "severity"],
                name="validator_v_validat_d037ae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationerror",
            index=models.Index(
                fields=["error_code"], name="validator_v_error_c_b87a28_idx"
            ),
        ),
    ]
