# Generated by Django 5.2.9 on 2025-12-29 17:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("priority", models.IntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "pricing tier",
                "verbose_name_plural": "pricing tiers",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_prices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "CUSTOMER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_prices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_prices",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "customer product price",
                "verbose_name_plural": "customer product prices",
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=["customer", "product", "is_active"],
                        name="pricing_cus_custome_968b23_idx",
                    ),
                    models.Index(
                        fields=["effective_date", "expiration_date"],
                        name="pricing_cus_effecti_f06979_idx",
                    ),
                ],
                "unique_together": {("customer", "product", "effective_date")},
            },
        ),
        migrations.CreateModel(
            name="TierProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_prices",
                        to="products.product",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_prices",
                        to="pricing.pricingtier",
                    ),
                ),
            ],
            options={
                "verbose_name": "tier product price",
                "verbose_name_plural": "tier product prices",
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=["tier", "is_active"],
                        name="pricing_tie_tier_id_1f3888_idx",
                    ),
                    models.Index(
                        fields=["product", "is_active"],
                        name="pricing_tie_product_223521_idx",
                    ),
                ],
                "unique_together": {("tier", "product", "effective_date")},
            },
        ),
        migrations.CreateModel(
            name="VolumeDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minimum_quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for category-wide discount",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volume_discounts",
                        to="products.product",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for universal discount",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volume_discounts",
                        to="pricing.pricingtier",
                    ),
                ),
            ],
            options={
                "verbose_name": "volume discount",
                "verbose_name_plural": "volume discounts",
                "ordering": ["minimum_quantity"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"],
                        name="pricing_vol_product_18ee3e_idx",
                    ),
                    models.Index(
                        fields=["tier", "is_active"],
                        name="pricing_vol_tier_id_b8f3f3_idx",
                    ),
                ],
            },
        ),
    ]
