# Generated by Django 5.2.9 on 2025-12-29 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcesApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_file", models.TextField()),
                ("app_id", models.BigIntegerField(db_index=True)),
                ("action", models.CharField(max_length=1)),
                ("validate", models.BooleanField(default=True)),
                ("part_number", models.CharField(db_index=True, max_length=45)),
                ("part_type_id", models.IntegerField(db_index=True)),
                ("quantity", models.IntegerField(null=True)),
                ("position_id", models.IntegerField(null=True)),
                ("brand_aaiaid", models.CharField(max_length=4, null=True)),
                ("subbrand_aaiaid", models.CharField(max_length=4, null=True)),
                ("mfr_label", models.TextField(null=True)),
                ("display_order", models.IntegerField(null=True)),
                ("asset_name", models.CharField(max_length=45, null=True)),
                ("asset_item_order", models.IntegerField(null=True)),
                ("asset_item_ref", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": '"autocare_aces"."app"',
            },
        ),
        migrations.CreateModel(
            name="AcesAspiration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aspiration_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."aspiration"',
            },
        ),
        migrations.CreateModel(
            name="AcesBedLength",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bed_length_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."bed_length"',
            },
        ),
        migrations.CreateModel(
            name="AcesBedType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bed_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."bed_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesBodyNumDoors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_num_doors_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."body_num_doors"',
            },
        ),
        migrations.CreateModel(
            name="AcesBodyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."body_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesBrakeAbs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brake_abs_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."brake_abs"',
            },
        ),
        migrations.CreateModel(
            name="AcesBrakeSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brake_system_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."brake_system"',
            },
        ),
        migrations.CreateModel(
            name="AcesCylinderHeadType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cylinder_head_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."cylinder_head_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesDriveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drive_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."drive_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesEngineBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine_base_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."engine_base"',
            },
        ),
        migrations.CreateModel(
            name="AcesEngineBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine_block_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."engine_block"',
            },
        ),
        migrations.CreateModel(
            name="AcesEngineBoreStroke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine_bore_stroke_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."engine_bore_stroke"',
            },
        ),
        migrations.CreateModel(
            name="AcesEngineDesignation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine_designation_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."engine_designation"',
            },
        ),
        migrations.CreateModel(
            name="AcesEngineMfr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine_mfr_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."engine_mfr"',
            },
        ),
        migrations.CreateModel(
            name="AcesEngineVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine_version_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."engine_version"',
            },
        ),
        migrations.CreateModel(
            name="AcesEngineVin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine_vin_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."engine_vin"',
            },
        ),
        migrations.CreateModel(
            name="AcesEquipmentBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_base_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."equipment_base"',
            },
        ),
        migrations.CreateModel(
            name="AcesEquipmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_model_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."equipment_model"',
            },
        ),
        migrations.CreateModel(
            name="AcesFrontBrakeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front_brake_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."front_brake_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesFrontSpringType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front_spring_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."front_spring_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesFuelDeliverySubType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fuel_delivery_sub_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."fuel_delivery_sub_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesFuelDeliveryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fuel_delivery_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."fuel_delivery_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesFuelSystemControlType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fuel_system_control_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."fuel_system_control_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesFuelSystemDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fuel_system_design_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."fuel_system_design"',
            },
        ),
        migrations.CreateModel(
            name="AcesFuelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fuel_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."fuel_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesIgnitionSystemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ignition_system_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."ignition_system_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesMfr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mfr_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."mfr"',
            },
        ),
        migrations.CreateModel(
            name="AcesMfrBodyCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mfr_body_code_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."mfr_body_code"',
            },
        ),
        migrations.CreateModel(
            name="AcesPowerOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("power_output_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."power_output"',
            },
        ),
        migrations.CreateModel(
            name="AcesQualifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qual_id", models.IntegerField(db_index=True)),
                ("qual_text", models.TextField(null=True)),
                ("param_1", models.TextField(null=True)),
                ("param_2", models.TextField(null=True)),
                ("param_3", models.TextField(null=True)),
            ],
            options={
                "db_table": '"autocare_aces"."qualifier"',
            },
        ),
        migrations.CreateModel(
            name="AcesRawAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attr_name", models.CharField(db_index=True, max_length=64)),
                ("attr_id", models.IntegerField(null=True)),
                ("attr_value", models.TextField(null=True)),
                ("idx", models.IntegerField(default=0)),
            ],
            options={
                "db_table": '"autocare_aces"."raw_attribute"',
            },
        ),
        migrations.CreateModel(
            name="AcesRearBrakeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rear_brake_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."rear_brake_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesRearSpringType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rear_spring_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."rear_spring_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."region"',
            },
        ),
        migrations.CreateModel(
            name="AcesSteeringSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("steering_system_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."steering_system"',
            },
        ),
        migrations.CreateModel(
            name="AcesSteeringType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("steering_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."steering_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesTransElecControlled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trans_elec_controlled_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."trans_elec_controlled"',
            },
        ),
        migrations.CreateModel(
            name="AcesTransmissionBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transmission_base_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."transmission_base"',
            },
        ),
        migrations.CreateModel(
            name="AcesTransmissionControlType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transmission_control_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."transmission_control_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesTransmissionMfr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transmission_mfr_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."transmission_mfr"',
            },
        ),
        migrations.CreateModel(
            name="AcesTransmissionMfrCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transmission_mfr_code_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."transmission_mfr_code"',
            },
        ),
        migrations.CreateModel(
            name="AcesTransmissionNumSpeeds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transmission_num_speeds_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."transmission_num_speeds"',
            },
        ),
        migrations.CreateModel(
            name="AcesTransmissionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transmission_type_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."transmission_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesValvesPerEngine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valves_per_engine_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."valves_per_engine"',
            },
        ),
        migrations.CreateModel(
            name="AcesVehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_type_id", models.IntegerField(db_index=True)),
                ("idx", models.IntegerField(default=0)),
            ],
            options={
                "db_table": '"autocare_aces"."vehicle_type"',
            },
        ),
        migrations.CreateModel(
            name="AcesWheelBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wheel_base_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": '"autocare_aces"."wheel_base"',
            },
        ),
        migrations.CreateModel(
            name="AcesAppVehicle",
            fields=[
                (
                    "app",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="autocare_aces.acesapp",
                    ),
                ),
                ("year_from", models.IntegerField(db_index=True, null=True)),
                ("year_to", models.IntegerField(db_index=True, null=True)),
                ("engine_base_id", models.IntegerField(db_index=True, null=True)),
                ("engine_block_id", models.IntegerField(db_index=True, null=True)),
                ("engine_vin_id", models.IntegerField(db_index=True, null=True)),
                ("aspiration_id", models.IntegerField(db_index=True, null=True)),
                ("transmission_base_id", models.IntegerField(db_index=True, null=True)),
                ("transmission_type_id", models.IntegerField(db_index=True, null=True)),
                ("drive_type_id", models.IntegerField(db_index=True, null=True)),
                ("fuel_type_id", models.IntegerField(db_index=True, null=True)),
                ("equipment_base_id", models.IntegerField(db_index=True, null=True)),
                ("equipment_model_id", models.IntegerField(db_index=True, null=True)),
                ("mfr_id", models.IntegerField(db_index=True, null=True)),
                ("production_year_start", models.IntegerField(null=True)),
                ("production_year_end", models.IntegerField(null=True)),
            ],
            options={
                "db_table": '"autocare_aces"."app_vehicle"',
            },
        ),
        migrations.AddIndex(
            model_name="acesapp",
            index=models.Index(fields=["part_number"], name="app_part_nu_e626f0_idx"),
        ),
        migrations.AddIndex(
            model_name="acesapp",
            index=models.Index(fields=["part_type_id"], name="app_part_ty_7607d2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="acesapp",
            unique_together={("source_file", "app_id")},
        ),
        migrations.AddField(
            model_name="acesaspiration",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesbedlength",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesbedtype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesbodynumdoors",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesbodytype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesbrakeabs",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesbrakesystem",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acescylinderheadtype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesdrivetype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesenginebase",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesengineblock",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesengineborestroke",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesenginedesignation",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesenginemfr",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesengineversion",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesenginevin",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesequipmentbase",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesequipmentmodel",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesfrontbraketype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesfrontspringtype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesfueldeliverysubtype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesfueldeliverytype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesfuelsystemcontroltype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesfuelsystemdesign",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesfueltype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesignitionsystemtype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesmfr",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesmfrbodycode",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acespoweroutput",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesqualifier",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualifiers",
                to="autocare_aces.acesapp",
            ),
        ),
        migrations.AddField(
            model_name="acesrawattribute",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_attributes",
                to="autocare_aces.acesapp",
            ),
        ),
        migrations.AddField(
            model_name="acesrearbraketype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesrearspringtype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesregion",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acessteeringsystem",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acessteeringtype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acestranseleccontrolled",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acestransmissionbase",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acestransmissioncontroltype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acestransmissionmfr",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acestransmissionmfrcode",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acestransmissionnumspeeds",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acestransmissiontype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesvalvesperengine",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
        migrations.AddField(
            model_name="acesvehicletype",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_types",
                to="autocare_aces.acesapp",
            ),
        ),
        migrations.AddField(
            model_name="aceswheelbase",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autocare_aces.acesapp"
            ),
        ),
    ]
