# Generated by Django 5.2.9 on 2025-12-29 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autocare_aces", "0001_initial"),
        ("autocare_vcdb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="acesappvehicle",
            name="base_vehicle",
            field=models.ForeignKey(
                blank=True,
                db_column="BaseVehicleID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="aces_applications",
                to="autocare_vcdb.basevehicle",
            ),
        ),
        migrations.AddField(
            model_name="acesappvehicle",
            name="make",
            field=models.ForeignKey(
                blank=True,
                db_column="MakeID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="aces_applications",
                to="autocare_vcdb.make",
            ),
        ),
        migrations.AddField(
            model_name="acesappvehicle",
            name="model",
            field=models.ForeignKey(
                blank=True,
                db_column="ModelID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="aces_applications",
                to="autocare_vcdb.vehiclemodel",
            ),
        ),
        migrations.AddField(
            model_name="acesappvehicle",
            name="submodel",
            field=models.ForeignKey(
                blank=True,
                db_column="SubModelID",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="aces_applications",
                to="autocare_vcdb.submodel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="acesaspiration",
            unique_together={("app", "aspiration_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesbedlength",
            unique_together={("app", "bed_length_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesbedtype",
            unique_together={("app", "bed_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesbodynumdoors",
            unique_together={("app", "body_num_doors_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesbodytype",
            unique_together={("app", "body_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesbrakeabs",
            unique_together={("app", "brake_abs_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesbrakesystem",
            unique_together={("app", "brake_system_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acescylinderheadtype",
            unique_together={("app", "cylinder_head_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesdrivetype",
            unique_together={("app", "drive_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesenginebase",
            unique_together={("app", "engine_base_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesengineblock",
            unique_together={("app", "engine_block_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesengineborestroke",
            unique_together={("app", "engine_bore_stroke_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesenginedesignation",
            unique_together={("app", "engine_designation_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesenginemfr",
            unique_together={("app", "engine_mfr_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesengineversion",
            unique_together={("app", "engine_version_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesenginevin",
            unique_together={("app", "engine_vin_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesequipmentbase",
            unique_together={("app", "equipment_base_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesequipmentmodel",
            unique_together={("app", "equipment_model_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesfrontbraketype",
            unique_together={("app", "front_brake_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesfrontspringtype",
            unique_together={("app", "front_spring_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesfueldeliverysubtype",
            unique_together={("app", "fuel_delivery_sub_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesfueldeliverytype",
            unique_together={("app", "fuel_delivery_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesfuelsystemcontroltype",
            unique_together={("app", "fuel_system_control_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesfuelsystemdesign",
            unique_together={("app", "fuel_system_design_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesfueltype",
            unique_together={("app", "fuel_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesignitionsystemtype",
            unique_together={("app", "ignition_system_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesmfr",
            unique_together={("app", "mfr_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesmfrbodycode",
            unique_together={("app", "mfr_body_code_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acespoweroutput",
            unique_together={("app", "power_output_id")},
        ),
        migrations.AddIndex(
            model_name="acesqualifier",
            index=models.Index(fields=["qual_id"], name="qualifier_qual_id_6ef13f_idx"),
        ),
        migrations.AddIndex(
            model_name="acesrawattribute",
            index=models.Index(
                fields=["attr_name"], name="raw_attribu_attr_na_e740a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="acesrawattribute",
            index=models.Index(
                fields=["app", "attr_name", "idx"], name="raw_attribu_app_id_1f95f5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="acesrearbraketype",
            unique_together={("app", "rear_brake_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesrearspringtype",
            unique_together={("app", "rear_spring_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesregion",
            unique_together={("app", "region_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acessteeringsystem",
            unique_together={("app", "steering_system_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acessteeringtype",
            unique_together={("app", "steering_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acestranseleccontrolled",
            unique_together={("app", "trans_elec_controlled_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acestransmissionbase",
            unique_together={("app", "transmission_base_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acestransmissioncontroltype",
            unique_together={("app", "transmission_control_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acestransmissionmfr",
            unique_together={("app", "transmission_mfr_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acestransmissionmfrcode",
            unique_together={("app", "transmission_mfr_code_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acestransmissionnumspeeds",
            unique_together={("app", "transmission_num_speeds_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acestransmissiontype",
            unique_together={("app", "transmission_type_id")},
        ),
        migrations.AlterUniqueTogether(
            name="acesvalvesperengine",
            unique_together={("app", "valves_per_engine_id")},
        ),
        migrations.AddIndex(
            model_name="acesvehicletype",
            index=models.Index(
                fields=["app", "idx"], name="vehicle_typ_app_id_fd404c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="acesvehicletype",
            index=models.Index(
                fields=["vehicle_type_id"], name="vehicle_typ_vehicle_e27d76_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aceswheelbase",
            unique_together={("app", "wheel_base_id")},
        ),
    ]
