# Generated by Django 5.2.9 on 2025-12-29 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("common", "0001_initial"),
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerpricingtier",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_assignments",
                to="pricing.pricingtier",
            ),
        ),
        migrations.AddField(
            model_name="customerpricingtier",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "CUSTOMER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_tiers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pendingapproval",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Sales rep who reviewed this registration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pendingapproval",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_approval",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="common.address",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type", "is_active"], name="accounts_us_user_ty_029544_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["customer_number"], name="accounts_us_custome_1888f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["employee_id"], name="accounts_us_employe_0cbd94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerpricingtier",
            index=models.Index(
                fields=["user", "is_active"], name="accounts_cu_user_id_08c1df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerpricingtier",
            index=models.Index(
                fields=["effective_date", "expiration_date"],
                name="accounts_cu_effecti_c0734d_idx",
            ),
        ),
    ]
