#!/usr/bin/env python3
from pathlib import Path

BASE_DIR = Path("apps/autocare/models")

DATABASES = {
    "vcdb": [
        "Year",
        "Make",
        "Model",
        "SubModel",
        "Region",
        "VehicleType",
        "VehicleTypeGroup",
        "Class",
        "DriveType",
        "FuelType",
        "TransmissionType",
        "TransmissionControlType",
        "TransmissionNumSpeeds",
        "SteeringType",
        "SteeringSystem",
        "BrakeType",
        "BrakeSystem",
        "BrakeABS",
        "SpringType",
        "Valves",
        "Aspiration",
        "CylinderHeadType",
        "EngineBlock",
        "EngineBoreStroke",
        "EngineBase",
        "EngineConfig",
        "TransmissionBase",
        "BrakeConfig",
        "SteeringConfig",
        "SpringTypeConfig",
        "BodyStyleConfig",
        "BaseVehicle",
        "Vehicle",
        "VehicleToEngineConfig",
        "VehicleToTransmission",
        "VehicleToBodyConfig",
        "VehicleToDriveType",
        "VehicleToBedConfig",
        "VehicleToWheelBase",
    ],
    "pcdb": [],
    "padb": [],
    "qdb": [],
}


def snake_case(name: str) -> str:
    out = []
    for i, c in enumerate(name):
        if c.isupper() and i > 0:
            out.append("_")
        out.append(c.lower())
    return "".join(out)


def ensure_file(path: Path, content: str = ""):
    if not path.exists():
        path.write_text(content)


def main():
    BASE_DIR.mkdir(parents=True, exist_ok=True)
    ensure_file(BASE_DIR / "__init__.py")

    for db, models in DATABASES.items():
        db_dir = BASE_DIR / db
        db_dir.mkdir(exist_ok=True)
        ensure_file(db_dir / "__init__.py")

        for model in models:
            filename = snake_case(model) + ".py"
            file_path = db_dir / filename

            ensure_file(
                file_path,
                f"""from django.db import models


class {model}(models.Model):
    \"\"\"{model} model (autogenerated placeholder).\"\"\"

    class Meta:
        managed = False
        db_table = "autocare_{db}.{snake_case(model)}"
""",
            )

    print("Autocare model structure generated successfully.")


if __name__ == "__main__":
    main()
