# Generated by Django 5.2.9 on 2025-12-29 19:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "vehicle make",
                "verbose_name_plural": "vehicle makes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PIESItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pies_item_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("brand_label", models.CharField(db_index=True, max_length=100)),
                ("hazmat_code", models.CharField(blank=True, max_length=50)),
                ("package_uom", models.CharField(blank=True, max_length=50)),
                ("quantity_per_package", models.IntegerField(default=1)),
                (
                    "package_height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "package_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "package_width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "package_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "shipping_height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "shipping_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "shipping_width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "shipping_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("country_of_origin", models.CharField(blank=True, max_length=100)),
                (
                    "replacement_part_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("vmrs_code", models.CharField(blank=True, max_length=50)),
                ("unspsc_code", models.CharField(blank=True, max_length=50)),
                ("pies_version", models.CharField(default="7.2", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pies_data",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "PIES item",
                "verbose_name_plural": "PIES items",
            },
        ),
        migrations.CreateModel(
            name="PIESDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description_type",
                    models.CharField(
                        choices=[
                            ("SHO", "Short Description"),
                            ("LON", "Long Description"),
                            ("EXT", "Extended Description"),
                            ("MKT", "Marketing Description"),
                            ("FEA", "Features"),
                            ("WAR", "Warranty"),
                        ],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                ("description_text", models.TextField()),
                (
                    "language_code",
                    models.CharField(db_index=True, default="EN", max_length=10),
                ),
                ("sequence", models.IntegerField(default=1)),
                (
                    "pies_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="aces_pies.piesitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "PIES description",
                "verbose_name_plural": "PIES descriptions",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="aces_pies.vehiclemake",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle model",
                "verbose_name_plural": "vehicle models",
                "ordering": ["make__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="VehicleApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                (
                    "submodel",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "engine_base",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("engine_designation", models.CharField(blank=True, max_length=100)),
                (
                    "engine_vin",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                (
                    "liter",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("cylinders", models.IntegerField(blank=True, null=True)),
                ("block_type", models.CharField(blank=True, max_length=10)),
                (
                    "fuel_type",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("drive_type", models.CharField(blank=True, max_length=50)),
                ("transmission", models.CharField(blank=True, max_length=100)),
                (
                    "body_type",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("bed_length", models.CharField(blank=True, max_length=50)),
                ("wheelbase", models.CharField(blank=True, max_length=50)),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Front, Rear, Left, Right",
                        max_length=100,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("note", models.TextField(blank=True)),
                ("qualifier", models.CharField(blank=True, max_length=500)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("aces_version", models.CharField(default="5.0", max_length=10)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_applications",
                        to="products.product",
                    ),
                ),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="aces_pies.vehiclemake",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="aces_pies.vehiclemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle application",
                "verbose_name_plural": "vehicle applications",
                "ordering": ["-year", "make__name", "model__name"],
            },
        ),
        migrations.AddIndex(
            model_name="piesitem",
            index=models.Index(
                fields=["pies_item_number"], name="aces_pies_p_pies_it_8f0998_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="piesitem",
            index=models.Index(
                fields=["brand_label"], name="aces_pies_p_brand_l_77da84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="piesitem",
            index=models.Index(
                fields=["replacement_part_number"],
                name="aces_pies_p_replace_e6e0d2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="piesdescription",
            unique_together={
                ("pies_item", "description_type", "language_code", "sequence")
            },
        ),
        migrations.AddIndex(
            model_name="vehiclemodel",
            index=models.Index(
                fields=["make", "name"], name="aces_pies_v_make_id_1199e5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vehiclemodel",
            unique_together={("make", "code")},
        ),
        migrations.AddIndex(
            model_name="vehicleapplication",
            index=models.Index(
                fields=["product", "is_active"], name="aces_pies_v_product_570238_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleapplication",
            index=models.Index(
                fields=["make", "model", "year"], name="aces_pies_v_make_id_326c75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleapplication",
            index=models.Index(
                fields=["year", "make"], name="aces_pies_v_year_6c467d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleapplication",
            index=models.Index(
                fields=["engine_base"], name="aces_pies_v_engine__95e02d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleapplication",
            index=models.Index(
                fields=["engine_vin"], name="aces_pies_v_engine__892a5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleapplication",
            index=models.Index(
                fields=["fuel_type"], name="aces_pies_v_fuel_ty_d5d003_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleapplication",
            index=models.Index(
                fields=["body_type"], name="aces_pies_v_body_ty_c561ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleapplication",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="aces_pies_v_search__15e46d_gin"
            ),
        ),
    ]
