# Generated by Django 5.2.9 on 2025-12-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset", models.CharField(db_index=True, max_length=10)),
                ("endpoint_key", models.CharField(db_index=True, max_length=120)),
                ("as_of_date", models.DateField(db_index=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": '"autocare_shared"."ingest_state"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AutocareRawRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_db",
                    models.CharField(
                        choices=[
                            ("vcdb", "VCdb"),
                            ("pcdb", "PCdb"),
                            ("padb", "PAdb"),
                            ("qdb", "Qdb"),
                        ],
                        max_length=10,
                    ),
                ),
                ("endpoint_key", models.CharField(db_index=True, max_length=120)),
                ("request_path", models.CharField(max_length=255)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("as_of_date", models.CharField(blank=True, max_length=20, null=True)),
                ("since_date", models.CharField(blank=True, max_length=20, null=True)),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("page_size", models.IntegerField(blank=True, null=True)),
                ("http_status", models.IntegerField()),
                ("record_count", models.IntegerField(blank=True, null=True)),
                ("payload", models.JSONField()),
                (
                    "ingestion_mode",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("full", "Full"),
                            ("incremental", "Incremental"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "autocare_autocarerawrecord",
                "indexes": [
                    models.Index(
                        fields=["source_db", "endpoint_key"],
                        name="autocare_au_source__aa17b8_idx",
                    ),
                    models.Index(
                        fields=["fetched_at"], name="autocare_au_fetched_b8aa07_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_db",
                            "endpoint_key",
                            "since_date",
                            "as_of_date",
                            "page_number",
                            "page_size",
                        ),
                        name="unique_autocare_ingest_page",
                    )
                ],
            },
        ),
    ]
