# Generated by Django 5.2.9 on 2025-12-29 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ACESCodedValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "element",
                    models.CharField(
                        blank=True, db_column="Element", max_length=255, null=True
                    ),
                ),
                (
                    "attribute",
                    models.CharField(
                        blank=True, db_column="Attribute", max_length=255, null=True
                    ),
                ),
                (
                    "coded_value",
                    models.CharField(
                        blank=True, db_column="CodedValue", max_length=255, null=True
                    ),
                ),
                (
                    "code_description",
                    models.CharField(
                        blank=True,
                        db_column="CodeDescription",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "ACESCodedValues",
                "verbose_name_plural": "ACESCodedValuess",
                "db_table": '"autocare_pcdb"."ACESCodedValues"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "version_date",
                    models.DateTimeField(
                        blank=True, db_column="VersionDate", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Version",
                "verbose_name_plural": "Versions",
                "db_table": '"autocare_pcdb"."Version"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "alias_id",
                    models.IntegerField(
                        db_column="AliasID", primary_key=True, serialize=False
                    ),
                ),
                ("alias_name", models.CharField(db_column="AliasName", max_length=100)),
            ],
            options={
                "verbose_name": "Alias",
                "verbose_name_plural": "Aliass",
                "db_table": '"autocare_pcdb"."Alias"',
                "managed": True,
                "indexes": [
                    models.Index(fields=["alias_id"], name="Alias_AliasID_07b52a_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "category_id",
                    models.IntegerField(
                        db_column="CategoryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "category_name",
                    models.CharField(db_column="CategoryName", max_length=500),
                ),
            ],
            options={
                "verbose_name": "Categories",
                "verbose_name_plural": "Categoriess",
                "db_table": '"autocare_pcdb"."Categories"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["category_id"], name="Categories_Categor_dff634_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChangeAttributeStates",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "change_attribute_state_id",
                    models.IntegerField(
                        db_column="ChangeAttributeStateID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_attribute_state",
                    models.CharField(db_column="ChangeAttributeState", max_length=255),
                ),
            ],
            options={
                "verbose_name": "ChangeAttributeStates",
                "verbose_name_plural": "ChangeAttributeStatess",
                "db_table": '"autocare_pcdb"."ChangeAttributeStates"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["change_attribute_state_id"],
                        name="ChangeAttri_ChangeA_f5cc66_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChangeReasons",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "change_reason_id",
                    models.IntegerField(
                        db_column="ChangeReasonID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(db_column="ChangeReason", max_length=255),
                ),
            ],
            options={
                "verbose_name": "ChangeReasons",
                "verbose_name_plural": "ChangeReasonss",
                "db_table": '"autocare_pcdb"."ChangeReasons"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["change_reason_id"],
                        name="ChangeReaso_ChangeR_ba1c42_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Changes",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "change_id",
                    models.IntegerField(
                        db_column="ChangeID", primary_key=True, serialize=False
                    ),
                ),
                ("request_id", models.IntegerField(db_column="RequestID")),
                (
                    "rev_date",
                    models.DateTimeField(blank=True, db_column="RevDate", null=True),
                ),
                (
                    "change_reason",
                    models.ForeignKey(
                        db_column="ChangeReasonID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_pcdb.changereasons",
                    ),
                ),
            ],
            options={
                "verbose_name": "Changes",
                "verbose_name_plural": "Changess",
                "db_table": '"autocare_pcdb"."Changes"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ChangeTableNames",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "table_name_id",
                    models.IntegerField(
                        db_column="TableNameID", primary_key=True, serialize=False
                    ),
                ),
                ("table_name", models.CharField(db_column="TableName", max_length=255)),
                (
                    "table_description",
                    models.CharField(
                        blank=True,
                        db_column="TableDescription",
                        max_length=1000,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "ChangeTableNames",
                "verbose_name_plural": "ChangeTableNamess",
                "db_table": '"autocare_pcdb"."ChangeTableNames"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["table_name_id"], name="ChangeTable_TableNa_41f150_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChangeDetails",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "change_detail_id",
                    models.IntegerField(
                        db_column="ChangeDetailID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "primary_key_column_name",
                    models.CharField(
                        blank=True,
                        db_column="PrimaryKeyColumnName",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "primary_key_before",
                    models.IntegerField(
                        blank=True, db_column="PrimaryKeyBefore", null=True
                    ),
                ),
                (
                    "primary_key_after",
                    models.IntegerField(
                        blank=True, db_column="PrimaryKeyAfter", null=True
                    ),
                ),
                (
                    "column_name",
                    models.CharField(
                        blank=True, db_column="ColumnName", max_length=255, null=True
                    ),
                ),
                (
                    "column_value_before",
                    models.CharField(
                        blank=True,
                        db_column="ColumnValueBefore",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "column_value_after",
                    models.CharField(
                        blank=True,
                        db_column="ColumnValueAfter",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "change_attribute_state",
                    models.ForeignKey(
                        db_column="ChangeAttributeStateID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_pcdb.changeattributestates",
                    ),
                ),
                (
                    "change",
                    models.ForeignKey(
                        db_column="ChangeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_pcdb.changes",
                    ),
                ),
                (
                    "table_name",
                    models.ForeignKey(
                        db_column="TableNameID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_pcdb.changetablenames",
                    ),
                ),
            ],
            options={
                "verbose_name": "ChangeDetails",
                "verbose_name_plural": "ChangeDetailss",
                "db_table": '"autocare_pcdb"."ChangeDetails"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PartCategory",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "part_category_id",
                    models.IntegerField(
                        db_column="PartCategoryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "part_terminology_id",
                    models.IntegerField(db_column="PartTerminologyID", db_index=True),
                ),
                (
                    "subcategory_id",
                    models.IntegerField(db_column="SubCategoryID", db_index=True),
                ),
                (
                    "category_id",
                    models.IntegerField(db_column="CategoryID", db_index=True),
                ),
            ],
            options={
                "verbose_name": "PartCategory",
                "verbose_name_plural": "PartCategories",
                "db_table": '"autocare_pcdb"."PartCategory"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["part_terminology_id"],
                        name="PartCategor_PartTer_35cba6_idx",
                    ),
                    models.Index(
                        fields=["subcategory_id"], name="PartCategor_SubCate_b35883_idx"
                    ),
                    models.Index(
                        fields=["category_id"], name="PartCategor_Categor_539189_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartPosition",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "part_position_id",
                    models.IntegerField(
                        db_column="PartPositionID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "part_terminology_id",
                    models.IntegerField(db_column="PartTerminologyID", db_index=True),
                ),
                (
                    "position_id",
                    models.IntegerField(db_column="PositionID", db_index=True),
                ),
                (
                    "rev_date",
                    models.DateField(blank=True, db_column="RevDate", null=True),
                ),
            ],
            options={
                "verbose_name": "PartPosition",
                "verbose_name_plural": "PartPositions",
                "db_table": '"autocare_pcdb"."PartPosition"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["part_terminology_id"],
                        name="PartPositio_PartTer_a885d5_idx",
                    ),
                    models.Index(
                        fields=["position_id"], name="PartPositio_Positio_6fd50c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Parts",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "part_terminology_id",
                    models.IntegerField(
                        db_column="PartTerminologyID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "part_terminology_name",
                    models.CharField(db_column="PartTerminologyName", max_length=500),
                ),
                (
                    "parts_description_id",
                    models.IntegerField(
                        blank=True,
                        db_column="PartsDescriptionID",
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "rev_date",
                    models.DateField(blank=True, db_column="RevDate", null=True),
                ),
            ],
            options={
                "db_table": '"autocare_pcdb"."Parts"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["part_terminology_id"], name="Parts_PartTer_e5d5f8_idx"
                    ),
                    models.Index(
                        fields=["parts_description_id"], name="Parts_PartsDe_638ea8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartsDescription",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "parts_description_id",
                    models.IntegerField(
                        db_column="PartsDescriptionID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parts_description",
                    models.CharField(
                        blank=True,
                        db_column="PartsDescription",
                        max_length=1000,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "PartsDescription",
                "verbose_name_plural": "PartsDescriptions",
                "db_table": '"autocare_pcdb"."PartsDescription"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["parts_description_id"],
                        name="PartsDescri_PartsDe_8059d4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PartsRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "part_terminology",
                    models.ForeignKey(
                        db_column="PartTerminologyID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_pcdb.parts",
                    ),
                ),
                (
                    "related_part_terminology",
                    models.ForeignKey(
                        db_column="RelatedPartTerminologyID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="related_part_relationships",
                        to="autocare_pcdb.parts",
                    ),
                ),
            ],
            options={
                "verbose_name": "PartsRelationship",
                "verbose_name_plural": "PartsRelationships",
                "db_table": '"autocare_pcdb"."PartsRelationship"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PartsSupersession",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "old_part_terminology_id",
                    models.IntegerField(
                        db_column="OldPartTerminologyID", db_index=True
                    ),
                ),
                (
                    "old_part_terminology_name",
                    models.CharField(
                        db_column="OldPartTerminologyName", max_length=200
                    ),
                ),
                (
                    "new_part_terminology_id",
                    models.IntegerField(db_column="NewPartTerminologyID"),
                ),
                (
                    "new_part_terminology_name",
                    models.CharField(
                        db_column="NewPartTerminologyName", max_length=200
                    ),
                ),
                (
                    "rev_date",
                    models.DateField(blank=True, db_column="RevDate", null=True),
                ),
            ],
            options={
                "db_table": '"autocare_pcdb"."PartsSupersession"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["old_part_terminology_id"],
                        name="PartsSupers_OldPart_cd7cb8_idx",
                    ),
                    models.Index(
                        fields=["new_part_terminology_id"],
                        name="PartsSupers_NewPart_4e742e_idx",
                    ),
                ],
                "unique_together": {
                    ("old_part_terminology_id", "new_part_terminology_id", "rev_date")
                },
            },
        ),
        migrations.CreateModel(
            name="PartsToAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "alias",
                    models.ForeignKey(
                        db_column="AliasID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_pcdb.alias",
                    ),
                ),
                (
                    "part_terminology",
                    models.ForeignKey(
                        db_column="PartTerminologyID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_pcdb.parts",
                    ),
                ),
            ],
            options={
                "verbose_name": "PartsToAlias",
                "verbose_name_plural": "PartsToAliass",
                "db_table": '"autocare_pcdb"."PartsToAlias"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PIESCode",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "pies_code_id",
                    models.IntegerField(
                        blank=True, db_column="PIESCodeId", db_index=True, null=True
                    ),
                ),
                ("code_value", models.CharField(db_column="CodeValue", max_length=500)),
                (
                    "code_format",
                    models.CharField(db_column="CodeFormat", max_length=500),
                ),
                (
                    "field_format",
                    models.CharField(
                        blank=True, db_column="FieldFormat", max_length=500, null=True
                    ),
                ),
                (
                    "code_description",
                    models.CharField(db_column="CodeDescription", max_length=500),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, db_column="Source", max_length=500, null=True
                    ),
                ),
            ],
            options={
                "db_table": '"autocare_pcdb"."PIESCode"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["pies_code_id"], name="PIESCode_PIESCod_dcb52f_idx"
                    )
                ],
                "unique_together": {
                    ("pies_code_id", "code_value", "code_format", "source")
                },
            },
        ),
        migrations.CreateModel(
            name="PIESExpiGroup",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "pies_expi_group_id",
                    models.IntegerField(
                        blank=True,
                        db_column="PIESExpiGroupId",
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "expi_group_code",
                    models.CharField(db_column="ExpiGroupCode", max_length=500),
                ),
                (
                    "expi_group_description",
                    models.CharField(db_column="ExpiGroupDescription", max_length=500),
                ),
            ],
            options={
                "verbose_name": "PIES Expi Group",
                "verbose_name_plural": "PIES Expi Groups",
                "db_table": '"autocare_pcdb"."PIESExpiGroup"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["pies_expi_group_id"],
                        name="PIESExpiGro_PIESExp_8db5a6_idx",
                    )
                ],
                "unique_together": {("pies_expi_group_id", "expi_group_code")},
            },
        ),
        migrations.CreateModel(
            name="PIESExpiCode",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "pies_expi_code_id",
                    models.IntegerField(
                        blank=True, db_column="PIESExpiCodeId", db_index=True, null=True
                    ),
                ),
                ("expi_code", models.CharField(db_column="ExpiCode", max_length=100)),
                (
                    "expi_code_description",
                    models.CharField(db_column="ExpiCodeDescription", max_length=500),
                ),
                (
                    "pies_expi_group",
                    models.ForeignKey(
                        blank=True,
                        db_column="PIESExpiGroupId",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_pcdb.piesexpigroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "PIES Expi Code",
                "verbose_name_plural": "PIES Expi Codes",
                "db_table": '"autocare_pcdb"."PIESExpiCode"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PIESField",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "pies_field_id",
                    models.IntegerField(
                        blank=True, db_column="PIESFieldId", db_index=True, null=True
                    ),
                ),
                ("field_name", models.CharField(db_column="FieldName", max_length=500)),
                (
                    "reference_field_number",
                    models.CharField(db_column="ReferenceFieldNumber", max_length=500),
                ),
                (
                    "pies_segment_id",
                    models.IntegerField(
                        blank=True, db_column="PIESSegmentId", db_index=True, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "PIES Field",
                "verbose_name_plural": "PIES Fields",
                "db_table": '"autocare_pcdb"."PIESField"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["pies_field_id"], name="PIESField_PIESFie_183b96_idx"
                    ),
                    models.Index(
                        fields=["pies_segment_id"], name="PIESField_PIESSeg_74fe1a_idx"
                    ),
                ],
                "unique_together": {("pies_field_id", "reference_field_number")},
            },
        ),
        migrations.CreateModel(
            name="PIESReferenceFieldCode",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "pies_reference_field_code_id",
                    models.IntegerField(
                        blank=True,
                        db_column="PIESReferenceFieldCodeId",
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "pies_field_id",
                    models.IntegerField(
                        blank=True, db_column="PIESFieldId", db_index=True, null=True
                    ),
                ),
                (
                    "pies_code_id",
                    models.IntegerField(
                        blank=True, db_column="PIESCodeId", db_index=True, null=True
                    ),
                ),
                (
                    "pies_expi_code_id",
                    models.IntegerField(
                        blank=True, db_column="PIESExpiCodeId", db_index=True, null=True
                    ),
                ),
                (
                    "reference_notes",
                    models.CharField(
                        blank=True,
                        db_column="ReferenceNotes",
                        max_length=2000,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": '"autocare_pcdb"."PIESReferenceFieldCode"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["pies_reference_field_code_id"],
                        name="PIESReferen_PIESRef_12d479_idx",
                    ),
                    models.Index(
                        fields=["pies_field_id"], name="PIESReferen_PIESFie_f4b383_idx"
                    ),
                    models.Index(
                        fields=["pies_code_id"], name="PIESReferen_PIESCod_dadf39_idx"
                    ),
                    models.Index(
                        fields=["pies_expi_code_id"],
                        name="PIESReferen_PIESExp_1d4ebc_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "pies_reference_field_code_id",
                        "pies_field_id",
                        "pies_code_id",
                        "pies_expi_code_id",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="PIESSegment",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "pies_segment_id",
                    models.IntegerField(
                        blank=True, db_column="PIESSegmentId", db_index=True, null=True
                    ),
                ),
                (
                    "segment_abb",
                    models.CharField(db_column="SegmentAbb", max_length=100),
                ),
                (
                    "segment_name",
                    models.CharField(db_column="SegmentName", max_length=100),
                ),
                (
                    "segment_description",
                    models.CharField(db_column="SegmentDescription", max_length=250),
                ),
            ],
            options={
                "db_table": '"autocare_pcdb"."PIESSegment"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["pies_segment_id"],
                        name="PIESSegment_PIESSeg_e6996b_idx",
                    )
                ],
                "unique_together": {("pies_segment_id", "segment_abb")},
            },
        ),
        migrations.CreateModel(
            name="Positions",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "position_id",
                    models.IntegerField(
                        db_column="PositionID", primary_key=True, serialize=False
                    ),
                ),
                ("position", models.CharField(db_column="Position", max_length=500)),
            ],
            options={
                "verbose_name": "Positions",
                "verbose_name_plural": "Positionss",
                "db_table": '"autocare_pcdb"."Positions"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["position_id"], name="Positions_Positio_3e502d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subcategories",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "sub_category_id",
                    models.IntegerField(
                        db_column="SubCategoryID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "sub_category_name",
                    models.CharField(db_column="SubCategoryName", max_length=500),
                ),
            ],
            options={
                "verbose_name": "Subcategories",
                "verbose_name_plural": "Subcategoriess",
                "db_table": '"autocare_pcdb"."Subcategories"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["sub_category_id"],
                        name="Subcategori_SubCate_4271a0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CodeMaster",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "code_master_id",
                    models.IntegerField(
                        db_column="CodeMasterID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "rev_date",
                    models.DateField(blank=True, db_column="RevDate", null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_column="CategoryID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_pcdb.categories",
                    ),
                ),
                (
                    "part_terminology",
                    models.ForeignKey(
                        db_column="PartTerminologyID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_pcdb.parts",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        db_column="PositionID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_pcdb.positions",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        db_column="SubCategoryID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_pcdb.subcategories",
                    ),
                ),
            ],
            options={
                "verbose_name": "CodeMaster",
                "verbose_name_plural": "CodeMasters",
                "db_table": '"autocare_pcdb"."CodeMaster"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Use",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "use_id",
                    models.IntegerField(
                        db_column="UseID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "use_description",
                    models.CharField(db_column="UseDescription", max_length=500),
                ),
            ],
            options={
                "verbose_name": "Use",
                "verbose_name_plural": "Uses",
                "db_table": '"autocare_pcdb"."Use"',
                "managed": True,
                "indexes": [
                    models.Index(fields=["use_id"], name="Use_UseID_b6baff_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PartsToUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "part_terminology",
                    models.ForeignKey(
                        db_column="PartTerminologyID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_pcdb.parts",
                    ),
                ),
                (
                    "use",
                    models.ForeignKey(
                        db_column="UseID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_pcdb.use",
                    ),
                ),
            ],
            options={
                "verbose_name": "PartsToUse",
                "verbose_name_plural": "PartsToUses",
                "db_table": '"autocare_pcdb"."PartsToUse"',
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="changes",
            index=models.Index(fields=["change_id"], name="Changes_ChangeI_daaae0_idx"),
        ),
        migrations.AddIndex(
            model_name="changedetails",
            index=models.Index(
                fields=["change_detail_id"], name="ChangeDetai_ChangeD_aebaee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partsrelationship",
            index=models.Index(
                fields=["part_terminology", "related_part_terminology"],
                name="PartsRelati_PartTer_ec4b85_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partstoalias",
            index=models.Index(
                fields=["part_terminology", "alias"],
                name="PartsToAlia_PartTer_1dbfce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="piesexpicode",
            index=models.Index(
                fields=["pies_expi_code_id"], name="PIESExpiCod_PIESExp_7c86b1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="piesexpicode",
            unique_together={("pies_expi_code_id", "expi_code")},
        ),
        migrations.AddIndex(
            model_name="codemaster",
            index=models.Index(
                fields=["code_master_id"], name="CodeMaster_CodeMas_721981_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partstouse",
            index=models.Index(
                fields=["part_terminology", "use"], name="PartsToUse_PartTer_247aa3_idx"
            ),
        ),
    ]
