# Generated by Django 5.2.9 on 2025-12-15 18:41

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Abbreviation",
            fields=[
                (
                    "abbreviation",
                    models.CharField(
                        db_index=True, max_length=3, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.CharField(max_length=20)),
                ("long_description", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Abbreviation",
                "verbose_name_plural": "Abbreviations",
                "db_table": "autocare_vcdb.abbreviation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alias_id", models.IntegerField(db_index=True, unique=True)),
                ("alias_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Alias",
                "verbose_name_plural": "Aliases",
                "db_table": "autocare_pcdb.alias",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Aspiration",
            fields=[
                (
                    "aspiration_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("aspiration_name", models.CharField(db_index=True, max_length=30)),
            ],
            options={
                "verbose_name": "Aspiration",
                "verbose_name_plural": "Aspirations",
                "db_table": "autocare_vcdb.aspiration",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "attachment_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("attachment_file_name", models.CharField(max_length=50)),
                ("attachment_url", models.CharField(max_length=100)),
                ("attachment_description", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "db_table": "autocare_vcdb.attachment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AttachmentType",
            fields=[
                (
                    "attachment_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("attachment_type_name", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Attachment Type",
                "verbose_name_plural": "Attachment Types",
                "db_table": "autocare_vcdb.attachment_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BaseVehicle",
            fields=[
                (
                    "base_vehicle_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Vehicle",
                "verbose_name_plural": "Base Vehicles",
                "db_table": "autocare_vcdb.base_vehicle",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BedConfig",
            fields=[
                (
                    "bed_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Bed Config",
                "verbose_name_plural": "Bed Configs",
                "db_table": "autocare_vcdb.bed_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BedLength",
            fields=[
                (
                    "bed_length_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("bed_length", models.CharField(max_length=10)),
                ("bed_length_metric", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Bed Length",
                "verbose_name_plural": "Bed Lengths",
                "db_table": "autocare_vcdb.bed_length",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BedType",
            fields=[
                (
                    "bed_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("bed_type_name", models.CharField(db_index=True, max_length=50)),
            ],
            options={
                "verbose_name": "Bed Type",
                "verbose_name_plural": "Bed Types",
                "db_table": "autocare_vcdb.bed_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BodyNumDoors",
            fields=[
                (
                    "body_num_doors_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("body_num_doors", models.CharField(max_length=3)),
            ],
            options={
                "verbose_name": "Body Number of Doors",
                "verbose_name_plural": "Body Number of Doors",
                "db_table": "autocare_vcdb.body_num_doors",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BodyStyleConfig",
            fields=[
                (
                    "body_style_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Body Style Config",
                "verbose_name_plural": "Body Style Configs",
                "db_table": "autocare_vcdb.body_style_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BodyType",
            fields=[
                (
                    "body_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("body_type_name", models.CharField(db_index=True, max_length=50)),
            ],
            options={
                "verbose_name": "Body Type",
                "verbose_name_plural": "Body Types",
                "db_table": "autocare_vcdb.body_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BrakeABS",
            fields=[
                (
                    "brake_abs_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("brake_abs_name", models.CharField(db_index=True, max_length=30)),
            ],
            options={
                "verbose_name": "Brake ABS",
                "verbose_name_plural": "Brake ABS",
                "db_table": "autocare_vcdb.brake_abs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BrakeConfig",
            fields=[
                (
                    "brake_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Brake Config",
                "verbose_name_plural": "Brake Configs",
                "db_table": "autocare_vcdb.brake_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BrakeSystem",
            fields=[
                (
                    "brake_system_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("brake_system_name", models.CharField(db_index=True, max_length=30)),
            ],
            options={
                "verbose_name": "Brake System",
                "verbose_name_plural": "Brake Systems",
                "db_table": "autocare_vcdb.brake_system",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BrakeType",
            fields=[
                (
                    "brake_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("brake_type_name", models.CharField(db_index=True, max_length=30)),
            ],
            options={
                "verbose_name": "Brake Type",
                "verbose_name_plural": "Brake Types",
                "db_table": "autocare_vcdb.brake_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category_id", models.IntegerField(db_index=True, unique=True)),
                ("category_name", models.CharField(db_index=True, max_length=100)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "autocare_pcdb.category",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChangeAttributeStates",
            fields=[
                (
                    "change_attribute_state_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("change_attribute_state", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Change Attribute State",
                "verbose_name_plural": "Change Attribute States",
                "db_table": "autocare_vcdb.change_attribute_states",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChangeDetails",
            fields=[
                (
                    "change_detail_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "primary_key_column_name",
                    models.CharField(max_length=255, null=True),
                ),
                ("primary_key_before", models.IntegerField(null=True)),
                ("primary_key_after", models.IntegerField(null=True)),
                ("column_name", models.CharField(max_length=255, null=True)),
                ("column_value_before", models.CharField(max_length=1000, null=True)),
                ("column_value_after", models.CharField(max_length=1000, null=True)),
            ],
            options={
                "verbose_name": "Change Detail",
                "verbose_name_plural": "Change Details",
                "db_table": "autocare_vcdb.change_details",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChangeReasons",
            fields=[
                (
                    "change_reason_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("change_reason", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Change Reason",
                "verbose_name_plural": "Change Reasons",
                "db_table": "autocare_vcdb.change_reasons",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Changes",
            fields=[
                (
                    "change_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("request_id", models.IntegerField()),
                ("rev_date", models.DateTimeField(null=True)),
            ],
            options={
                "verbose_name": "Change",
                "verbose_name_plural": "Changes",
                "db_table": "autocare_vcdb.changes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChangeTableNames",
            fields=[
                (
                    "table_name_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("table_name", models.CharField(max_length=255)),
                ("table_description", models.CharField(max_length=1000, null=True)),
            ],
            options={
                "verbose_name": "Change Table Name",
                "verbose_name_plural": "Change Table Names",
                "db_table": "autocare_vcdb.change_table_names",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CodeMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_master_id", models.IntegerField(db_index=True, unique=True)),
                ("rev_date", models.DateField()),
            ],
            options={
                "verbose_name": "Code Master",
                "verbose_name_plural": "Code Masters",
                "db_table": "autocare_pcdb.code_master",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CylinderHeadType",
            fields=[
                (
                    "cylinder_head_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "cylinder_head_type_name",
                    models.CharField(db_index=True, max_length=30),
                ),
            ],
            options={
                "verbose_name": "Cylinder Head Type",
                "verbose_name_plural": "Cylinder Head Types",
                "db_table": "autocare_vcdb.cylinder_head_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DriveType",
            fields=[
                (
                    "drive_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("drive_type_name", models.CharField(db_index=True, max_length=30)),
            ],
            options={
                "verbose_name": "Drive Type",
                "verbose_name_plural": "Drive Types",
                "db_table": "autocare_vcdb.drive_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ElecControlled",
            fields=[
                (
                    "elec_controlled_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("elec_controlled", models.CharField(db_index=True, max_length=3)),
            ],
            options={
                "verbose_name": "Electrically Controlled",
                "verbose_name_plural": "Electrically Controlled",
                "db_table": "autocare_vcdb.elec_controlled",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EngineBase",
            fields=[
                (
                    "engine_base_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("liter", models.CharField(max_length=6)),
                ("cc", models.CharField(max_length=8)),
                ("cid", models.CharField(max_length=7)),
                ("cylinders", models.CharField(max_length=2)),
                ("block_type", models.CharField(max_length=2)),
                ("eng_bore_in", models.CharField(max_length=10)),
                ("eng_bore_metric", models.CharField(max_length=10)),
                ("eng_stroke_in", models.CharField(max_length=10)),
                ("eng_stroke_metric", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Engine Base",
                "verbose_name_plural": "Engine Bases",
                "db_table": "autocare_vcdb.engine_base",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EngineBase2",
            fields=[
                (
                    "engine_base_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Engine Base 2",
                "verbose_name_plural": "Engine Bases 2",
                "db_table": "autocare_vcdb.engine_base2",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EngineBlock",
            fields=[
                (
                    "engine_block_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("liter", models.CharField(max_length=6)),
                ("cc", models.CharField(max_length=8)),
                ("cid", models.CharField(max_length=7)),
                ("cylinders", models.CharField(max_length=2)),
                ("block_type", models.CharField(max_length=2)),
            ],
            options={
                "verbose_name": "Engine Block",
                "verbose_name_plural": "Engine Blocks",
                "db_table": "autocare_vcdb.engine_block",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EngineBoreStroke",
            fields=[
                (
                    "engine_bore_stroke_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("eng_bore_in", models.CharField(max_length=10)),
                ("eng_bore_metric", models.CharField(max_length=10)),
                ("eng_stroke_in", models.CharField(max_length=10)),
                ("eng_stroke_metric", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Engine Bore Stroke",
                "verbose_name_plural": "Engine Bore Strokes",
                "db_table": "autocare_vcdb.engine_bore_stroke",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EngineConfig",
            fields=[
                (
                    "engine_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Engine Config",
                "verbose_name_plural": "Engine Configs",
                "db_table": "autocare_vcdb.engine_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EngineConfig2",
            fields=[
                (
                    "engine_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Engine Config 2",
                "verbose_name_plural": "Engine Configs 2",
                "db_table": "autocare_vcdb.engine_config2",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EngineDesignation",
            fields=[
                (
                    "engine_designation_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "engine_designation_name",
                    models.CharField(db_index=True, max_length=30),
                ),
            ],
            options={
                "verbose_name": "Engine Designation",
                "verbose_name_plural": "Engine Designations",
                "db_table": "autocare_vcdb.engine_designation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EngineVersion",
            fields=[
                (
                    "engine_version_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("engine_version", models.CharField(db_index=True, max_length=20)),
            ],
            options={
                "verbose_name": "Engine Version",
                "verbose_name_plural": "Engine Versions",
                "db_table": "autocare_vcdb.engine_version",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EngineVIN",
            fields=[
                (
                    "engine_vin_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("engine_vin_name", models.CharField(db_index=True, max_length=5)),
            ],
            options={
                "verbose_name": "Engine VIN",
                "verbose_name_plural": "Engine VINs",
                "db_table": "autocare_vcdb.engine_vin",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EnglishPhrase",
            fields=[
                (
                    "english_phrase_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("english_phrase", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "English Phrase",
                "verbose_name_plural": "English Phrases",
                "db_table": "autocare_vcdb.english_phrase",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FuelDeliveryConfig",
            fields=[
                (
                    "fuel_delivery_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuel Delivery Config",
                "verbose_name_plural": "Fuel Delivery Configs",
                "db_table": "autocare_vcdb.fuel_delivery_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FuelDeliverySubType",
            fields=[
                (
                    "fuel_delivery_sub_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "fuel_delivery_sub_type_name",
                    models.CharField(db_index=True, max_length=50),
                ),
            ],
            options={
                "verbose_name": "Fuel Delivery Sub Type",
                "verbose_name_plural": "Fuel Delivery Sub Types",
                "db_table": "autocare_vcdb.fuel_delivery_sub_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FuelDeliveryType",
            fields=[
                (
                    "fuel_delivery_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "fuel_delivery_type_name",
                    models.CharField(db_index=True, max_length=50),
                ),
            ],
            options={
                "verbose_name": "Fuel Delivery Type",
                "verbose_name_plural": "Fuel Delivery Types",
                "db_table": "autocare_vcdb.fuel_delivery_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FuelSystemControlType",
            fields=[
                (
                    "fuel_system_control_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "fuel_system_control_type_name",
                    models.CharField(db_index=True, max_length=50),
                ),
            ],
            options={
                "verbose_name": "Fuel System Control Type",
                "verbose_name_plural": "Fuel System Control Types",
                "db_table": "autocare_vcdb.fuel_system_control_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FuelSystemDesign",
            fields=[
                (
                    "fuel_system_design_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "fuel_system_design_name",
                    models.CharField(db_index=True, max_length=50),
                ),
            ],
            options={
                "verbose_name": "Fuel System Design",
                "verbose_name_plural": "Fuel System Designs",
                "db_table": "autocare_vcdb.fuel_system_design",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FuelType",
            fields=[
                (
                    "fuel_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("fuel_type_name", models.CharField(db_index=True, max_length=30)),
            ],
            options={
                "verbose_name": "Fuel Type",
                "verbose_name_plural": "Fuel Types",
                "db_table": "autocare_vcdb.fuel_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GroupNumber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_number_id", models.IntegerField(db_index=True, unique=True)),
                ("group_description", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Group Number",
                "verbose_name_plural": "Group Numbers",
                "db_table": "autocare_qdb.group_number",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IgnitionSystemType",
            fields=[
                (
                    "ignition_system_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "ignition_system_type_name",
                    models.CharField(db_index=True, max_length=30),
                ),
            ],
            options={
                "verbose_name": "Ignition System Type",
                "verbose_name_plural": "Ignition System Types",
                "db_table": "autocare_vcdb.ignition_system_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "language_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("language_name", models.CharField(max_length=20)),
                ("dialect_name", models.CharField(max_length=20, null=True)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "autocare_vcdb.language",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LanguageTranslation",
            fields=[
                (
                    "language_translation_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("translation", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Language Translation",
                "verbose_name_plural": "Language Translations",
                "db_table": "autocare_vcdb.language_translation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LanguageTranslationAttachment",
            fields=[
                (
                    "language_translation_attachment_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Language Translation Attachment",
                "verbose_name_plural": "Language Translation Attachments",
                "db_table": "autocare_vcdb.language_translation_attachment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Make",
            fields=[
                (
                    "make_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("make_name", models.CharField(db_index=True, max_length=50)),
            ],
            options={
                "verbose_name": "Make",
                "verbose_name_plural": "Makes",
                "db_table": "autocare_vcdb.make",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MeasurementGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "measurement_group_id",
                    models.IntegerField(db_index=True, unique=True),
                ),
                ("measurement_group_name", models.CharField(max_length=80, null=True)),
            ],
            options={
                "verbose_name": "Measurement Group",
                "verbose_name_plural": "Measurement Groups",
                "db_table": "autocare_padb.measurement_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MetaData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("meta_id", models.IntegerField(db_index=True, unique=True)),
                ("meta_name", models.CharField(max_length=80, null=True)),
                ("meta_descr", models.CharField(max_length=512, null=True)),
                ("meta_format", models.CharField(max_length=10, null=True)),
                ("data_type", models.CharField(max_length=50, null=True)),
                ("min_length", models.IntegerField(null=True)),
                ("max_length", models.IntegerField(null=True)),
            ],
            options={
                "verbose_name": "Meta Data",
                "verbose_name_plural": "Meta Data",
                "db_table": "autocare_padb.metadata",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MetaUOMCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("meta_uom_id", models.IntegerField(db_index=True, unique=True)),
                ("uom_code", models.CharField(max_length=10, null=True)),
                ("uom_description", models.CharField(max_length=512, null=True)),
                ("uom_label", models.CharField(max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Meta UOM Code",
                "verbose_name_plural": "Meta UOM Codes",
                "db_table": "autocare_padb.meta_uom_code",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MetaUomCodeAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meta_uom_code_assignment_id",
                    models.IntegerField(db_index=True, unique=True),
                ),
            ],
            options={
                "verbose_name": "Meta UOM Code Assignment",
                "verbose_name_plural": "Meta UOM Code Assignments",
                "db_table": "autocare_padb.meta_uom_code_assignment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mfr",
            fields=[
                (
                    "mfr_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("mfr_name", models.CharField(db_index=True, max_length=30)),
            ],
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
                "db_table": "autocare_vcdb.mfr",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MfrBodyCode",
            fields=[
                (
                    "mfr_body_code_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("mfr_body_code_name", models.CharField(db_index=True, max_length=10)),
            ],
            options={
                "verbose_name": "Manufacturer Body Code",
                "verbose_name_plural": "Manufacturer Body Codes",
                "db_table": "autocare_vcdb.mfr_body_code",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "model_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=100)),
            ],
            options={
                "verbose_name": "Model",
                "verbose_name_plural": "Models",
                "db_table": "autocare_vcdb.model",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PAdbVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_date", models.DateTimeField(db_index=True)),
                ("is_current", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "PAdb Version",
                "verbose_name_plural": "PAdb Versions",
                "db_table": "autocare_padb.padb_version",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PartAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pa_id", models.IntegerField(db_index=True, unique=True)),
                ("pa_name", models.CharField(max_length=80, null=True)),
                ("pa_descr", models.CharField(max_length=512, null=True)),
            ],
            options={
                "verbose_name": "Part Attribute",
                "verbose_name_plural": "Part Attributes",
                "db_table": "autocare_padb.part_attribute",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PartAttributeAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("papt_id", models.IntegerField(db_index=True, unique=True)),
                ("part_terminology_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "Part Attribute Assignment",
                "verbose_name_plural": "Part Attribute Assignments",
                "db_table": "autocare_padb.part_attribute_assignment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PartAttributeStyle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("style_id", models.IntegerField(null=True)),
            ],
            options={
                "verbose_name": "Part Attribute Style",
                "verbose_name_plural": "Part Attribute Styles",
                "db_table": "autocare_padb.part_attribute_style",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PartCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("part_category_id", models.IntegerField(db_index=True, unique=True)),
            ],
            options={
                "verbose_name": "Part Category",
                "verbose_name_plural": "Part Categories",
                "db_table": "autocare_pcdb.part_category",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PartPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("part_position_id", models.IntegerField(db_index=True, unique=True)),
                ("rev_date", models.DateField(null=True)),
            ],
            options={
                "verbose_name": "Part Position",
                "verbose_name_plural": "Part Positions",
                "db_table": "autocare_pcdb.part_position",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Parts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "part_terminology_id",
                    models.IntegerField(db_index=True, unique=True),
                ),
                (
                    "part_terminology_name",
                    models.CharField(db_index=True, max_length=500),
                ),
                ("rev_date", models.DateField(null=True)),
            ],
            options={
                "verbose_name": "Part",
                "verbose_name_plural": "Parts",
                "db_table": "autocare_pcdb.parts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PartsDescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parts_description_id",
                    models.IntegerField(db_index=True, unique=True),
                ),
                ("parts_description", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Parts Description",
                "verbose_name_plural": "Parts Descriptions",
                "db_table": "autocare_pcdb.parts_description",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PartsSupersession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parts_supersession_id",
                    models.IntegerField(db_index=True, unique=True),
                ),
                ("old_part_terminology_id", models.IntegerField()),
                ("old_part_terminology_name", models.CharField(max_length=256)),
                ("new_part_terminology_id", models.IntegerField()),
                ("new_part_terminology_name", models.CharField(max_length=256)),
                ("rev_date", models.DateField(null=True)),
                ("note", models.CharField(max_length=1000, null=True)),
            ],
            options={
                "verbose_name": "Parts Supersession",
                "verbose_name_plural": "Parts Supersessions",
                "db_table": "autocare_pcdb.parts_supersession",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PartsToAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parts to Alias",
                "verbose_name_plural": "Parts to Aliases",
                "db_table": "autocare_pcdb.parts_to_alias",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PartsToUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parts to Use",
                "verbose_name_plural": "Parts to Uses",
                "db_table": "autocare_pcdb.parts_to_use",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PartTypeStyle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("part_terminology_id", models.IntegerField(null=True)),
            ],
            options={
                "verbose_name": "Part Type Style",
                "verbose_name_plural": "Part Type Styles",
                "db_table": "autocare_padb.part_type_style",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PCdbVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_date", models.DateTimeField(db_index=True)),
                ("is_current", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "PCdb Version",
                "verbose_name_plural": "PCdb Versions",
                "db_table": "autocare_pcdb.pcdb_version",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position_id", models.IntegerField(db_index=True, unique=True)),
                ("position", models.CharField(db_index=True, max_length=500)),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "db_table": "autocare_pcdb.position",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PowerOutput",
            fields=[
                (
                    "power_output_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("horse_power", models.CharField(max_length=10)),
                ("kilowatt_power", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Power Output",
                "verbose_name_plural": "Power Outputs",
                "db_table": "autocare_vcdb.power_output",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PublicationStage",
            fields=[
                (
                    "publication_stage_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "publication_stage_name",
                    models.CharField(db_index=True, max_length=100),
                ),
            ],
            options={
                "verbose_name": "Publication Stage",
                "verbose_name_plural": "Publication Stages",
                "db_table": "autocare_vcdb.publication_stage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QdbVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_date", models.DateTimeField(db_index=True)),
                ("is_current", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Qdb Version",
                "verbose_name_plural": "Qdb Versions",
                "db_table": "autocare_qdb.qdb_version",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QLanguage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("language_id", models.IntegerField(db_index=True, unique=True)),
                ("language_name", models.CharField(max_length=50, null=True)),
                ("dialect_name", models.CharField(max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "autocare_qdb.language",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Qualifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qualifier_id", models.IntegerField(db_index=True, unique=True)),
                ("qualifier_text", models.CharField(max_length=500, null=True)),
                ("example_text", models.CharField(max_length=500, null=True)),
                ("when_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Qualifier",
                "verbose_name_plural": "Qualifiers",
                "db_table": "autocare_qdb.qualifier",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QualifierGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qualifier_group_id", models.IntegerField(db_index=True, unique=True)),
            ],
            options={
                "verbose_name": "Qualifier Group",
                "verbose_name_plural": "Qualifier Groups",
                "db_table": "autocare_qdb.qualifier_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QualifierTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qualifier_translation_id",
                    models.IntegerField(db_index=True, unique=True),
                ),
                ("translation_text", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Qualifier Translation",
                "verbose_name_plural": "Qualifier Translations",
                "db_table": "autocare_qdb.qualifier_translation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QualifierType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qualifier_type_id", models.IntegerField(db_index=True, unique=True)),
                ("qualifier_type", models.CharField(max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Qualifier Type",
                "verbose_name_plural": "Qualifier Types",
                "db_table": "autocare_qdb.qualifier_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "region_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("region_abbr", models.CharField(max_length=3, null=True)),
                ("region_name", models.CharField(db_index=True, max_length=30)),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "db_table": "autocare_vcdb.region",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SpringType",
            fields=[
                (
                    "spring_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("spring_type_name", models.CharField(db_index=True, max_length=50)),
            ],
            options={
                "verbose_name": "Spring Type",
                "verbose_name_plural": "Spring Types",
                "db_table": "autocare_vcdb.spring_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SpringTypeConfig",
            fields=[
                (
                    "spring_type_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Spring Type Config",
                "verbose_name_plural": "Spring Type Configs",
                "db_table": "autocare_vcdb.spring_type_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SteeringConfig",
            fields=[
                (
                    "steering_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Steering Config",
                "verbose_name_plural": "Steering Configs",
                "db_table": "autocare_vcdb.steering_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SteeringSystem",
            fields=[
                (
                    "steering_system_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "steering_system_name",
                    models.CharField(db_index=True, max_length=30),
                ),
            ],
            options={
                "verbose_name": "Steering System",
                "verbose_name_plural": "Steering Systems",
                "db_table": "autocare_vcdb.steering_system",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SteeringType",
            fields=[
                (
                    "steering_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("steering_type_name", models.CharField(db_index=True, max_length=30)),
            ],
            options={
                "verbose_name": "Steering Type",
                "verbose_name_plural": "Steering Types",
                "db_table": "autocare_vcdb.steering_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "style_id",
                    models.IntegerField(db_index=True, null=True, unique=True),
                ),
                ("style_name", models.CharField(max_length=225, null=True)),
            ],
            options={
                "verbose_name": "Style",
                "verbose_name_plural": "Styles",
                "db_table": "autocare_padb.style",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subcategory_id", models.IntegerField(db_index=True, unique=True)),
                ("subcategory_name", models.CharField(db_index=True, max_length=100)),
            ],
            options={
                "verbose_name": "Sub Category",
                "verbose_name_plural": "Sub Categories",
                "db_table": "autocare_pcdb.subcategory",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubModel",
            fields=[
                (
                    "sub_model_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("sub_model_name", models.CharField(db_index=True, max_length=50)),
            ],
            options={
                "verbose_name": "Sub Model",
                "verbose_name_plural": "Sub Models",
                "db_table": "autocare_vcdb.sub_model",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Transmission",
            fields=[
                (
                    "transmission_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Transmission",
                "verbose_name_plural": "Transmissions",
                "db_table": "autocare_vcdb.transmission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransmissionBase",
            fields=[
                (
                    "transmission_base_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Transmission Base",
                "verbose_name_plural": "Transmission Bases",
                "db_table": "autocare_vcdb.transmission_base",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransmissionControlType",
            fields=[
                (
                    "transmission_control_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "transmission_control_type_name",
                    models.CharField(db_index=True, max_length=30),
                ),
            ],
            options={
                "verbose_name": "Transmission Control Type",
                "verbose_name_plural": "Transmission Control Types",
                "db_table": "autocare_vcdb.transmission_control_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransmissionMfrCode",
            fields=[
                (
                    "transmission_mfr_code_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "transmission_mfr_code",
                    models.CharField(db_index=True, max_length=30),
                ),
            ],
            options={
                "verbose_name": "Transmission Manufacturer Code",
                "verbose_name_plural": "Transmission Manufacturer Codes",
                "db_table": "autocare_vcdb.transmission_mfr_code",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransmissionNumSpeeds",
            fields=[
                (
                    "transmission_num_speeds_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "transmission_num_speeds",
                    models.CharField(db_index=True, max_length=3),
                ),
            ],
            options={
                "verbose_name": "Transmission Number of Speeds",
                "verbose_name_plural": "Transmission Number of Speeds",
                "db_table": "autocare_vcdb.transmission_num_speeds",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransmissionType",
            fields=[
                (
                    "transmission_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "transmission_type_name",
                    models.CharField(db_index=True, max_length=30),
                ),
            ],
            options={
                "verbose_name": "Transmission Type",
                "verbose_name_plural": "Transmission Types",
                "db_table": "autocare_vcdb.transmission_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Use",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("use_id", models.IntegerField(db_index=True, unique=True)),
                ("use_description", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Use",
                "verbose_name_plural": "Uses",
                "db_table": "autocare_pcdb.use",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ValidValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valid_value_id", models.IntegerField(db_index=True, unique=True)),
                ("valid_value", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Valid Value",
                "verbose_name_plural": "Valid Values",
                "db_table": "autocare_padb.valid_value",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ValidValueAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "valid_value_assignment_id",
                    models.IntegerField(db_index=True, unique=True),
                ),
            ],
            options={
                "verbose_name": "Valid Value Assignment",
                "verbose_name_plural": "Valid Value Assignments",
                "db_table": "autocare_padb.valid_value_assignment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Valves",
            fields=[
                (
                    "valves_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("valves_per_engine", models.CharField(max_length=3)),
            ],
            options={
                "verbose_name": "Valves",
                "verbose_name_plural": "Valves",
                "db_table": "autocare_vcdb.valves",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VCdbChanges",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("version_date", models.DateTimeField()),
                ("table_name", models.CharField(max_length=30)),
                ("action", models.CharField(max_length=1)),
            ],
            options={
                "verbose_name": "VCdb Change",
                "verbose_name_plural": "VCdb Changes",
                "db_table": "autocare_vcdb.vcdb_changes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "vehicle_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source", models.CharField(max_length=10, null=True)),
                ("publication_stage_source", models.CharField(max_length=100)),
                (
                    "publication_stage_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "db_table": "autocare_vcdb.vehicle",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleClass",
            fields=[
                (
                    "class_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("class_name", models.CharField(db_index=True, max_length=30)),
            ],
            options={
                "verbose_name": "Vehicle Class",
                "verbose_name_plural": "Vehicle Classes",
                "db_table": "autocare_vcdb.class",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleToBedConfig",
            fields=[
                (
                    "vehicle_to_bed_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source", models.CharField(max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Vehicle to Bed Config",
                "verbose_name_plural": "Vehicle to Bed Configs",
                "db_table": "autocare_vcdb.vehicle_to_bed_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleToBodyConfig",
            fields=[
                (
                    "vehicle_to_body_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source", models.CharField(max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Vehicle to Body Config",
                "verbose_name_plural": "Vehicle to Body Configs",
                "db_table": "autocare_vcdb.vehicle_to_body_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleToBodyStyleConfig",
            fields=[
                (
                    "vehicle_to_body_style_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source", models.CharField(max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Vehicle to Body Style Config",
                "verbose_name_plural": "Vehicle to Body Style Configs",
                "db_table": "autocare_vcdb.vehicle_to_body_style_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleToBrakeConfig",
            fields=[
                (
                    "vehicle_to_brake_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source", models.CharField(max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Vehicle to Brake Config",
                "verbose_name_plural": "Vehicle to Brake Configs",
                "db_table": "autocare_vcdb.vehicle_to_brake_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleToClass",
            fields=[
                (
                    "vehicle_to_class_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source", models.CharField(max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Vehicle to Class",
                "verbose_name_plural": "Vehicle to Classes",
                "db_table": "autocare_vcdb.vehicle_to_class",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleToDriveType",
            fields=[
                (
                    "vehicle_to_drive_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source", models.CharField(max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Vehicle to Drive Type",
                "verbose_name_plural": "Vehicle to Drive Types",
                "db_table": "autocare_vcdb.vehicle_to_drive_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleToEngineConfig",
            fields=[
                (
                    "vehicle_to_engine_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source", models.CharField(max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Vehicle to Engine Config",
                "verbose_name_plural": "Vehicle to Engine Configs",
                "db_table": "autocare_vcdb.vehicle_to_engine_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleToMfrBodyCode",
            fields=[
                (
                    "vehicle_to_mfr_body_code_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source", models.CharField(max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Vehicle to Manufacturer Body Code",
                "verbose_name_plural": "Vehicle to Manufacturer Body Codes",
                "db_table": "autocare_vcdb.vehicle_to_mfr_body_code",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleToSpringTypeConfig",
            fields=[
                (
                    "vehicle_to_spring_type_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source", models.CharField(max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Vehicle to Spring Type Config",
                "verbose_name_plural": "Vehicle to Spring Type Configs",
                "db_table": "autocare_vcdb.vehicle_to_spring_type_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleToSteeringConfig",
            fields=[
                (
                    "vehicle_to_steering_config_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source", models.CharField(max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Vehicle to Steering Config",
                "verbose_name_plural": "Vehicle to Steering Configs",
                "db_table": "autocare_vcdb.vehicle_to_steering_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleToTransmission",
            fields=[
                (
                    "vehicle_to_transmission_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source", models.CharField(max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Vehicle to Transmission",
                "verbose_name_plural": "Vehicle to Transmissions",
                "db_table": "autocare_vcdb.vehicle_to_transmission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleToWheelBase",
            fields=[
                (
                    "vehicle_to_wheel_base_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("source", models.CharField(max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Vehicle to Wheel Base",
                "verbose_name_plural": "Vehicle to Wheel Bases",
                "db_table": "autocare_vcdb.vehicle_to_wheel_base",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "vehicle_type_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("vehicle_type_name", models.CharField(db_index=True, max_length=50)),
            ],
            options={
                "verbose_name": "Vehicle Type",
                "verbose_name_plural": "Vehicle Types",
                "db_table": "autocare_vcdb.vehicle_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleTypeGroup",
            fields=[
                (
                    "vehicle_type_group_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "vehicle_type_group_name",
                    models.CharField(db_index=True, max_length=50),
                ),
            ],
            options={
                "verbose_name": "Vehicle Type Group",
                "verbose_name_plural": "Vehicle Type Groups",
                "db_table": "autocare_vcdb.vehicle_type_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "version_date",
                    models.DateTimeField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Version",
                "verbose_name_plural": "Versions",
                "db_table": "autocare_vcdb.version",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WheelBase",
            fields=[
                (
                    "wheel_base_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("wheel_base", models.CharField(max_length=10)),
                ("wheel_base_metric", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Wheel Base",
                "verbose_name_plural": "Wheel Bases",
                "db_table": "autocare_vcdb.wheel_base",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "year_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Year",
                "verbose_name_plural": "Years",
                "db_table": "autocare_vcdb.year",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AutocareRawRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_db",
                    models.CharField(
                        choices=[
                            ("vcdb", "VCdb"),
                            ("pcdb", "PCdb"),
                            ("padb", "PAdb"),
                            ("qdb", "Qdb"),
                        ],
                        max_length=10,
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("as_of_date", models.DateField(blank=True, null=True)),
                ("since_date", models.DateField(blank=True, null=True)),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("page_size", models.IntegerField(blank=True, null=True)),
                ("http_status", models.IntegerField()),
                ("record_count", models.IntegerField(blank=True, null=True)),
                ("payload", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_db", "endpoint"],
                        name="autocare_au_source__694cbc_idx",
                    ),
                    models.Index(
                        fields=["fetched_at"], name="autocare_au_fetched_b8aa07_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source_db",
                            "endpoint",
                            "since_date",
                            "as_of_date",
                            "page_number",
                        ),
                        name="unique_autocare_ingest_page",
                    )
                ],
            },
        ),
    ]
