# Generated by Django 5.2.9 on 2025-12-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autocare", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="autocarerawrecord",
            name="unique_autocare_ingest_page",
        ),
        migrations.AddField(
            model_name="autocarerawrecord",
            name="ingestion_mode",
            field=models.CharField(
                choices=[
                    ("debug", "Debug"),
                    ("full", "Full"),
                    ("incremental", "Incremental"),
                ],
                default="full",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="autocarerawrecord",
            constraint=models.UniqueConstraint(
                fields=(
                    "source_db",
                    "endpoint",
                    "since_date",
                    "as_of_date",
                    "page_number",
                    "page_size",
                ),
                name="unique_autocare_ingest_page",
            ),
        ),
    ]
