# Generated by Django 5.2.9 on 2025-12-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autocare", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VehicleYear",
            new_name="Year",
        ),
    ]
