# Generated by Django 5.2.9 on 2025-12-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autocare", "0002_rename_vehicleyear_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="VCDBIngestState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=255, unique=True)),
                ("as_of_date", models.DateField()),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": '"autocare_vcdb"."ingest_state"',
            },
        ),
    ]
