# Generated by Django 5.2.9 on 2025-12-29 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("CSV", "CSV"),
                            ("EXCEL", "Excel (XLSX)"),
                            ("JSON", "JSON"),
                            ("XML", "XML"),
                            ("PDF", "PDF"),
                        ],
                        db_index=True,
                        default="CSV",
                        max_length=10,
                    ),
                ),
                (
                    "included_fields",
                    models.TextField(
                        help_text="Comma-separated list of field names to include"
                    ),
                ),
                (
                    "filter_config",
                    models.JSONField(
                        blank=True,
                        help_text="JSON configuration for filtering products",
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Available to all users"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "export template",
                "verbose_name_plural": "export templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("format", models.CharField(db_index=True, max_length=10)),
                ("total_records", models.IntegerField(default=0)),
                ("processed_records", models.IntegerField(default=0)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="exports/%Y/%m/%d/"
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_jobs",
                        to="exports.exporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "export job",
                "verbose_name_plural": "export jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("CUSTOM", "Custom Cron"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True, help_text="For custom frequency", max_length=100
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SFTP", "SFTP"),
                            ("DOWNLOAD", "Download Link"),
                            ("API", "API Callback"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("delivery_email", models.EmailField(blank=True, max_length=254)),
                ("delivery_sftp_path", models.CharField(blank=True, max_length=500)),
                ("delivery_api_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_exports",
                        to="exports.exporttemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "scheduled export",
                "verbose_name_plural": "scheduled exports",
                "ordering": ["next_run_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportDeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_method", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("recipient", models.CharField(blank=True, max_length=500)),
                ("error_message", models.TextField(blank=True)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "export_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="exports.exportjob",
                    ),
                ),
                (
                    "scheduled_export",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="exports.scheduledexport",
                    ),
                ),
            ],
            options={
                "verbose_name": "export delivery log",
                "verbose_name_plural": "export delivery logs",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                fields=["user", "status"], name="exports_exp_user_id_62d461_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                fields=["status", "created_at"], name="exports_exp_status_b76416_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledexport",
            index=models.Index(
                fields=["is_active", "next_run_at"],
                name="exports_sch_is_acti_fa07d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledexport",
            index=models.Index(
                fields=["user", "is_active"], name="exports_sch_user_id_0aba72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportdeliverylog",
            index=models.Index(
                fields=["status", "attempted_at"], name="exports_exp_status_4d9bd0_idx"
            ),
        ),
    ]
