# Generated by Django 5.2.9 on 2025-12-06 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "sync_interval_minutes",
                    models.IntegerField(
                        default=60, help_text="Sync interval in minutes"
                    ),
                ),
                ("filemaker_layout", models.CharField(max_length=200)),
                (
                    "filemaker_query",
                    models.TextField(
                        blank=True, help_text="FileMaker find/query criteria"
                    ),
                ),
                ("batch_size", models.IntegerField(default=100)),
                ("enable_incremental", models.BooleanField(default=True)),
                ("max_retries", models.IntegerField(default=3)),
                ("retry_delay_minutes", models.IntegerField(default=5)),
                ("notify_on_success", models.BooleanField(default=False)),
                ("notify_on_failure", models.BooleanField(default=True)),
                (
                    "notification_emails",
                    models.TextField(
                        blank=True, help_text="Comma-separated email addresses"
                    ),
                ),
                ("last_successful_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "sync configuration",
                "verbose_name_plural": "sync configurations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("filemaker_table", models.CharField(max_length=200)),
                ("filemaker_field", models.CharField(max_length=200)),
                (
                    "target_model",
                    models.CharField(
                        choices=[
                            ("PRODUCT", "Product"),
                            ("CATEGORY", "Product Category"),
                            ("MANUFACTURER", "Manufacturer"),
                            ("ATTRIBUTES", "Product Attributes"),
                            ("PRICING", "Pricing"),
                            ("ACES", "ACES Application"),
                            ("PIES", "PIES Data"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("target_field", models.CharField(max_length=200)),
                (
                    "transformation_function",
                    models.TextField(
                        blank=True,
                        help_text="Python function name or code for data transformation",
                    ),
                ),
                ("default_value", models.CharField(blank=True, max_length=500)),
                ("is_required", models.BooleanField(default=False)),
                ("validation_regex", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "data mapping",
                "verbose_name_plural": "data mappings",
                "ordering": ["filemaker_table", "filemaker_field"],
                "indexes": [
                    models.Index(
                        fields=["target_model", "is_active"],
                        name="data_sync_d_target__3fe289_idx",
                    )
                ],
                "unique_together": {
                    (
                        "filemaker_table",
                        "filemaker_field",
                        "target_model",
                        "target_field",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="SyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Sync"),
                            ("INCREMENTAL", "Incremental Sync"),
                            ("MANUAL", "Manual Sync"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "filemaker_layout",
                    models.CharField(
                        help_text="FileMaker layout/table name", max_length=200
                    ),
                ),
                (
                    "last_sync_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp from last successful sync",
                        null=True,
                    ),
                ),
                ("records_fetched", models.IntegerField(default=0)),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("records_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_sync_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sync job",
                "verbose_name_plural": "sync jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "sync_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="data_sync.syncjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "sync log",
                "verbose_name_plural": "sync logs",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="syncjob",
            index=models.Index(
                fields=["status", "created_at"], name="data_sync_s_status_a94eb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncjob",
            index=models.Index(
                fields=["sync_type", "status"], name="data_sync_s_sync_ty_05bb45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["sync_job", "level"], name="data_sync_s_sync_jo_735b09_idx"
            ),
        ),
    ]
