from __future__ import annotations

from django.db import models

# FINAL API-INGEST MODELS (Swagger + SQL merged)
# Generated by: manage.py generate_api_models

class Abbreviation(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    abbreviation = models.CharField(max_length=3, db_column='Abbreviation', primary_key=True)
    description = models.CharField(max_length=20, db_column='Description')
    long_description = models.CharField(max_length=200, db_column='LongDescription')

    class Meta:
        db_table = "autocare_vcdb.abbreviation"
        managed = True

class Aspiration(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    aspiration_id = models.IntegerField(db_column='AspirationID', primary_key=True)
    aspiration_name = models.CharField(max_length=30, db_column='AspirationName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.aspiration"
        managed = True

class BaseVehicle(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    base_vehicle_id = models.IntegerField(db_column='BaseVehicleID', primary_key=True)
    year = models.ForeignKey("Year", db_column="YearID", on_delete=models.DO_NOTHING, related_name="+")
    make = models.ForeignKey("Make", db_column="MakeID", on_delete=models.DO_NOTHING, related_name="+")
    model = models.ForeignKey("Model", db_column="ModelID", on_delete=models.DO_NOTHING, related_name="+")
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.base_vehicle"
        managed = True

class BedConfig(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    bed_config_id = models.IntegerField(db_column='BedConfigID', primary_key=True)
    bed_length = models.ForeignKey("BedLength", db_column="BedLengthID", on_delete=models.DO_NOTHING, related_name="+")
    bed_type = models.ForeignKey("BedType", db_column="BedTypeID", on_delete=models.DO_NOTHING, related_name="+")
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.bed_config"
        managed = True

class BedLength(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    bed_length_id = models.IntegerField(db_column='BedLengthID', primary_key=True)
    bed_length = models.CharField(max_length=10, db_column='BedLength')
    bed_length_metric = models.CharField(max_length=10, db_column='BedLengthMetric')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.bed_length"
        managed = True

class BedType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    bed_type_id = models.IntegerField(db_column='BedTypeID', primary_key=True)
    bed_type_name = models.CharField(max_length=50, db_column='BedTypeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.bed_type"
        managed = True

class BodyNumDoors(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    body_num_doors_id = models.IntegerField(db_column='BodyNumDoorsID', primary_key=True)
    body_num_doors = models.CharField(max_length=3, db_column='BodyNumDoors')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.body_num_doors"
        managed = True

class BodyStyleConfig(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    body_style_config_id = models.IntegerField(db_column='BodyStyleConfigID', primary_key=True)
    body_num_doors = models.ForeignKey("BodyNumDoors", db_column="BodyNumDoorsID", on_delete=models.DO_NOTHING, related_name="+")
    body_type = models.ForeignKey("BodyType", db_column="BodyTypeID", on_delete=models.DO_NOTHING, related_name="+")
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.body_style_config"
        managed = True

class BodyType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    body_type_id = models.IntegerField(db_column='BodyTypeID', primary_key=True)
    body_type_name = models.CharField(max_length=50, db_column='BodyTypeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.body_type"
        managed = True

class BrakeAbs(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    brake_absid = models.IntegerField(db_column='BrakeABSID', primary_key=True)
    brake_abs_name = models.CharField(max_length=30, db_column='BrakeABSName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.brake_abs"
        managed = True

class BrakeConfig(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    brake_config_id = models.IntegerField(db_column='BrakeConfigID', primary_key=True)
    front_brake_type = models.ForeignKey("BrakeType", db_column="FrontBrakeTypeID", on_delete=models.DO_NOTHING, related_name="+")
    rear_brake_type = models.ForeignKey("BrakeType", db_column="RearBrakeTypeID", on_delete=models.DO_NOTHING, related_name="+")
    brake_system = models.ForeignKey("BrakeSystem", db_column="BrakeSystemID", on_delete=models.DO_NOTHING, related_name="+")
    brake_abs = models.ForeignKey("BrakeAbs", db_column="BrakeABSID", on_delete=models.DO_NOTHING, related_name="+")
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.brake_config"
        managed = True

class BrakeSystem(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    brake_system_id = models.IntegerField(db_column='BrakeSystemID', primary_key=True)
    brake_system_name = models.CharField(max_length=30, db_column='BrakeSystemName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.brake_system"
        managed = True

class BrakeType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    brake_type_id = models.IntegerField(db_column='BrakeTypeID', primary_key=True)
    brake_type_name = models.CharField(max_length=30, db_column='BrakeTypeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.brake_type"
        managed = True

class ChangeAttributeStates(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    change_attribute_state_id = models.IntegerField(db_column='ChangeAttributeStateID', primary_key=True)
    change_attribute_state = models.CharField(max_length=255, db_column='ChangeAttributeState')

    class Meta:
        db_table = "autocare_vcdb.change_attribute_states"
        managed = True

class ChangeDetails(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    change_detail_id = models.IntegerField(db_column='ChangeDetailID', primary_key=True)
    change = models.ForeignKey("Changes", db_column="ChangeID", on_delete=models.DO_NOTHING, related_name="+")
    change_attribute_state = models.ForeignKey("ChangeAttributeStates", db_column="ChangeAttributeStateID", on_delete=models.DO_NOTHING, related_name="+")
    table_name = models.ForeignKey("ChangeTableNames", db_column="TableNameID", on_delete=models.DO_NOTHING, related_name="+")
    primary_key_column_name = models.CharField(max_length=255, null=True, blank=True, db_column='PrimaryKeyColumnName')
    primary_key_before = models.IntegerField(null=True, blank=True, db_column='PrimaryKeyBefore')
    primary_key_after = models.IntegerField(null=True, blank=True, db_column='PrimaryKeyAfter')
    column_name = models.CharField(max_length=255, null=True, blank=True, db_column='ColumnName')
    column_value_before = models.CharField(max_length=1000, null=True, blank=True, db_column='ColumnValueBefore')
    column_value_after = models.CharField(max_length=1000, null=True, blank=True, db_column='ColumnValueAfter')

    class Meta:
        db_table = "autocare_vcdb.change_details"
        managed = True

class ChangeReasons(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    change_reason_id = models.IntegerField(db_column='ChangeReasonID', primary_key=True)
    change_reason = models.CharField(max_length=255, db_column='ChangeReason')

    class Meta:
        db_table = "autocare_vcdb.change_reasons"
        managed = True

class ChangeTableNames(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    table_name_id = models.IntegerField(db_column='TableNameID', primary_key=True)
    table_name = models.CharField(max_length=255, db_column='TableName')
    table_description = models.CharField(max_length=1000, null=True, blank=True, db_column='TableDescription')

    class Meta:
        db_table = "autocare_vcdb.change_table_names"
        managed = True

class Changes(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    change_id = models.IntegerField(db_column='ChangeID', primary_key=True)
    request_id = models.IntegerField(db_column='RequestID')
    change_reason = models.ForeignKey("ChangeReasons", db_column="ChangeReasonID", on_delete=models.DO_NOTHING, related_name="+")
    rev_date = models.DateTimeField(null=True, blank=True, db_column='RevDate')

    class Meta:
        db_table = "autocare_vcdb.changes"
        managed = True

class ClassModel(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    class_id = models.IntegerField(db_column='ClassID', primary_key=True)
    class_name = models.CharField(max_length=30, db_column='ClassName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.class"
        managed = True

class CylinderHeadType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    cylinder_head_type_id = models.IntegerField(db_column='CylinderHeadTypeID', primary_key=True)
    cylinder_head_type_name = models.CharField(max_length=30, db_column='CylinderHeadTypeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.cylinder_head_type"
        managed = True

class DriveType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    drive_type_id = models.IntegerField(db_column='DriveTypeID', primary_key=True)
    drive_type_name = models.CharField(max_length=30, db_column='DriveTypeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.drive_type"
        managed = True

class ElecControlled(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    elec_controlled_id = models.IntegerField(db_column='ElecControlledID', primary_key=True)
    elec_controlled = models.CharField(max_length=3, db_column='ElecControlled')

    class Meta:
        db_table = "autocare_vcdb.elec_controlled"
        managed = True

class EngineBase(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    engine_base_id = models.IntegerField(db_column='EngineBaseID', primary_key=True)
    liter = models.CharField(max_length=6, db_column='Liter')
    cc = models.CharField(max_length=8, db_column='CC')
    cid = models.CharField(max_length=7, db_column='CID')
    cylinders = models.CharField(max_length=2, db_column='Cylinders')
    block_type = models.CharField(max_length=2, db_column='BlockType')
    eng_bore_in = models.CharField(max_length=10, db_column='EngBoreIn')
    eng_bore_metric = models.CharField(max_length=10, db_column='EngBoreMetric')
    eng_stroke_in = models.CharField(max_length=10, db_column='EngStrokeIn')
    eng_stroke_metric = models.CharField(max_length=10, db_column='EngStrokeMetric')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.engine_base"
        managed = True

class EngineBase2(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    engine_base_id = models.IntegerField(db_column='EngineBaseID', primary_key=True)
    engine_block = models.ForeignKey("EngineBlock", db_column="EngineBlockID", on_delete=models.DO_NOTHING, related_name="+")
    engine_bore_stroke = models.ForeignKey("EngineBoreStroke", db_column="EngineBoreStrokeID", on_delete=models.DO_NOTHING, related_name="+")
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.engine_base_2"
        managed = True

class EngineBlock(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    engine_block_id = models.IntegerField(db_column='EngineBlockID', primary_key=True)
    liter = models.CharField(max_length=6, db_column='Liter')
    cc = models.CharField(max_length=8, db_column='CC')
    cid = models.CharField(max_length=7, db_column='CID')
    cylinders = models.CharField(max_length=2, db_column='Cylinders')
    block_type = models.CharField(max_length=2, db_column='BlockType')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.engine_block"
        managed = True

class EngineBoreStroke(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    engine_bore_stroke_id = models.IntegerField(db_column='EngineBoreStrokeID', primary_key=True)
    eng_bore_in = models.CharField(max_length=10, db_column='EngBoreIn')
    eng_bore_metric = models.CharField(max_length=10, db_column='EngBoreMetric')
    eng_stroke_in = models.CharField(max_length=10, db_column='EngStrokeIn')
    eng_stroke_metric = models.CharField(max_length=10, db_column='EngStrokeMetric')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.engine_bore_stroke"
        managed = True

class EngineConfig(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    engine_config_id = models.IntegerField(db_column='EngineConfigID', primary_key=True)
    engine_designation = models.ForeignKey("EngineDesignation", db_column="EngineDesignationID", on_delete=models.DO_NOTHING, related_name="+")
    engine_vin = models.ForeignKey("EngineVin", db_column="EngineVINID", on_delete=models.DO_NOTHING, related_name="+")
    valves = models.ForeignKey("Valves", db_column="ValvesID", on_delete=models.DO_NOTHING, related_name="+")
    engine_base = models.ForeignKey("EngineBase", db_column="EngineBaseID", on_delete=models.DO_NOTHING, related_name="+")
    fuel_delivery_config = models.ForeignKey("FuelDeliveryConfig", db_column="FuelDeliveryConfigID", on_delete=models.DO_NOTHING, related_name="+")
    aspiration = models.ForeignKey("Aspiration", db_column="AspirationID", on_delete=models.DO_NOTHING, related_name="+")
    cylinder_head_type = models.ForeignKey("CylinderHeadType", db_column="CylinderHeadTypeID", on_delete=models.DO_NOTHING, related_name="+")
    fuel_type = models.ForeignKey("FuelType", db_column="FuelTypeID", on_delete=models.DO_NOTHING, related_name="+")
    ignition_system_type = models.ForeignKey("IgnitionSystemType", db_column="IgnitionSystemTypeID", on_delete=models.DO_NOTHING, related_name="+")
    engine_mfr = models.ForeignKey("Mfr", db_column="EngineMfrID", on_delete=models.DO_NOTHING, related_name="+")
    engine_version = models.ForeignKey("EngineVersion", db_column="EngineVersionID", on_delete=models.DO_NOTHING, related_name="+")
    power_output_id = models.IntegerField(db_column='PowerOutputID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.engine_config"
        managed = True

class EngineConfig2(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    engine_config_id = models.IntegerField(db_column='EngineConfigID', primary_key=True)
    engine_designation = models.ForeignKey("EngineDesignation", db_column="EngineDesignationID", on_delete=models.DO_NOTHING, related_name="+")
    engine_vin = models.ForeignKey("EngineVin", db_column="EngineVINID", on_delete=models.DO_NOTHING, related_name="+")
    valves = models.ForeignKey("Valves", db_column="ValvesID", on_delete=models.DO_NOTHING, related_name="+")
    engine_base = models.ForeignKey("EngineBase2", db_column="EngineBaseID", on_delete=models.DO_NOTHING, related_name="+")
    engine_block = models.ForeignKey("EngineBlock", db_column="EngineBlockID", on_delete=models.DO_NOTHING, related_name="+")
    engine_bore_stroke = models.ForeignKey("EngineBoreStroke", db_column="EngineBoreStrokeID", on_delete=models.DO_NOTHING, related_name="+")
    fuel_delivery_config = models.ForeignKey("FuelDeliveryConfig", db_column="FuelDeliveryConfigID", on_delete=models.DO_NOTHING, related_name="+")
    aspiration = models.ForeignKey("Aspiration", db_column="AspirationID", on_delete=models.DO_NOTHING, related_name="+")
    cylinder_head_type = models.ForeignKey("CylinderHeadType", db_column="CylinderHeadTypeID", on_delete=models.DO_NOTHING, related_name="+")
    fuel_type = models.ForeignKey("FuelType", db_column="FuelTypeID", on_delete=models.DO_NOTHING, related_name="+")
    ignition_system_type = models.ForeignKey("IgnitionSystemType", db_column="IgnitionSystemTypeID", on_delete=models.DO_NOTHING, related_name="+")
    engine_mfr = models.ForeignKey("Mfr", db_column="EngineMfrID", on_delete=models.DO_NOTHING, related_name="+")
    engine_version = models.ForeignKey("EngineVersion", db_column="EngineVersionID", on_delete=models.DO_NOTHING, related_name="+")
    power_output_id = models.IntegerField(db_column='PowerOutputID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.engine_config_2"
        managed = True

class EngineDesignation(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    engine_designation_id = models.IntegerField(db_column='EngineDesignationID', primary_key=True)
    engine_designation_name = models.CharField(max_length=30, db_column='EngineDesignationName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.engine_designation"
        managed = True

class EngineVin(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    engine_vinid = models.IntegerField(db_column='EngineVINID', primary_key=True)
    engine_vin_name = models.CharField(max_length=5, db_column='EngineVINName')

    class Meta:
        db_table = "autocare_vcdb.engine_vin"
        managed = True

class EngineVersion(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    engine_version_id = models.IntegerField(db_column='EngineVersionID', primary_key=True)
    engine_version = models.CharField(max_length=20, db_column='EngineVersion')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.engine_version"
        managed = True

class FuelDeliveryConfig(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    fuel_delivery_config_id = models.IntegerField(db_column='FuelDeliveryConfigID', primary_key=True)
    fuel_delivery_type = models.ForeignKey("FuelDeliveryType", db_column="FuelDeliveryTypeID", on_delete=models.DO_NOTHING, related_name="+")
    fuel_delivery_sub_type = models.ForeignKey("FuelDeliverySubType", db_column="FuelDeliverySubTypeID", on_delete=models.DO_NOTHING, related_name="+")
    fuel_system_control_type = models.ForeignKey("FuelSystemControlType", db_column="FuelSystemControlTypeID", on_delete=models.DO_NOTHING, related_name="+")
    fuel_system_design = models.ForeignKey("FuelSystemDesign", db_column="FuelSystemDesignID", on_delete=models.DO_NOTHING, related_name="+")
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.fuel_delivery_config"
        managed = True

class FuelDeliverySubType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    fuel_delivery_sub_type_id = models.IntegerField(db_column='FuelDeliverySubTypeID', primary_key=True)
    fuel_delivery_sub_type_name = models.CharField(max_length=50, db_column='FuelDeliverySubTypeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.fuel_delivery_sub_type"
        managed = True

class FuelDeliveryType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    fuel_delivery_type_id = models.IntegerField(db_column='FuelDeliveryTypeID', primary_key=True)
    fuel_delivery_type_name = models.CharField(max_length=50, db_column='FuelDeliveryTypeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.fuel_delivery_type"
        managed = True

class FuelSystemControlType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    fuel_system_control_type_id = models.IntegerField(db_column='FuelSystemControlTypeID', primary_key=True)
    fuel_system_control_type_name = models.CharField(max_length=50, db_column='FuelSystemControlTypeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.fuel_system_control_type"
        managed = True

class FuelSystemDesign(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    fuel_system_design_id = models.IntegerField(db_column='FuelSystemDesignID', primary_key=True)
    fuel_system_design_name = models.CharField(max_length=50, db_column='FuelSystemDesignName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.fuel_system_design"
        managed = True

class FuelType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    fuel_type_id = models.IntegerField(db_column='FuelTypeID', primary_key=True)
    fuel_type_name = models.CharField(max_length=30, db_column='FuelTypeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.fuel_type"
        managed = True

class IgnitionSystemType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    ignition_system_type_id = models.IntegerField(db_column='IgnitionSystemTypeID', primary_key=True)
    ignition_system_type_name = models.CharField(max_length=30, db_column='IgnitionSystemTypeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.ignition_system_type"
        managed = True

class Make(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    make_id = models.IntegerField(db_column='MakeID', primary_key=True)
    make_name = models.CharField(max_length=50, db_column='MakeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.make"
        managed = True

class Mfr(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    mfr_id = models.IntegerField(db_column='MfrID', primary_key=True)
    mfr_name = models.CharField(max_length=30, db_column='MfrName')

    class Meta:
        db_table = "autocare_vcdb.mfr"
        managed = True

class MfrBodyCode(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    mfr_body_code_id = models.IntegerField(db_column='MfrBodyCodeID', primary_key=True)
    mfr_body_code_name = models.CharField(max_length=10, db_column='MfrBodyCodeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.mfr_body_code"
        managed = True

class Model(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    model_id = models.IntegerField(db_column='ModelID', primary_key=True)
    model_name = models.CharField(null=True, blank=True, max_length=100, db_column='ModelName')
    vehicle_type = models.ForeignKey("VehicleType", db_column="VehicleTypeID", on_delete=models.DO_NOTHING, related_name="+")
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.model"
        managed = True

class PowerOutput(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    power_output_id = models.IntegerField(db_column='PowerOutputID')
    horse_power = models.CharField(max_length=10, db_column='HorsePower')
    kilowatt_power = models.CharField(max_length=10, db_column='KilowattPower')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.power_output"
        managed = True

class PublicationStage(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    publication_stage_id = models.IntegerField(db_column='PublicationStageID', primary_key=True)
    publication_stage_name = models.CharField(max_length=100, db_column='PublicationStageName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.publication_stage"
        managed = True

class Region(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    region_id = models.IntegerField(db_column='RegionID', primary_key=True)
    parent = models.ForeignKey("Region", db_column="ParentID", on_delete=models.DO_NOTHING, related_name="+", null=True, blank=True)
    region_abbr = models.CharField(null=True, blank=True, max_length=3, db_column='RegionAbbr')
    region_name = models.CharField(null=True, blank=True, max_length=30, db_column='RegionName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.region"
        managed = True

class SpringType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    spring_type_id = models.IntegerField(db_column='SpringTypeID', primary_key=True)
    spring_type_name = models.CharField(max_length=50, db_column='SpringTypeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.spring_type"
        managed = True

class SpringTypeConfig(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    spring_type_config_id = models.IntegerField(db_column='SpringTypeConfigID', primary_key=True)
    front_spring_type = models.ForeignKey("SpringType", db_column="FrontSpringTypeID", on_delete=models.DO_NOTHING, related_name="+")
    rear_spring_type = models.ForeignKey("SpringType", db_column="RearSpringTypeID", on_delete=models.DO_NOTHING, related_name="+")

    class Meta:
        db_table = "autocare_vcdb.spring_type_config"
        managed = True

class SteeringConfig(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    steering_config_id = models.IntegerField(db_column='SteeringConfigID', primary_key=True)
    steering_type = models.ForeignKey("SteeringType", db_column="SteeringTypeID", on_delete=models.DO_NOTHING, related_name="+")
    steering_system = models.ForeignKey("SteeringSystem", db_column="SteeringSystemID", on_delete=models.DO_NOTHING, related_name="+")
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.steering_config"
        managed = True

class SteeringSystem(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    steering_system_id = models.IntegerField(db_column='SteeringSystemID', primary_key=True)
    steering_system_name = models.CharField(max_length=30, db_column='SteeringSystemName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.steering_system"
        managed = True

class SteeringType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    steering_type_id = models.IntegerField(db_column='SteeringTypeID', primary_key=True)
    steering_type_name = models.CharField(max_length=30, db_column='SteeringTypeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.steering_type"
        managed = True

class SubModel(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    submodel_id = models.IntegerField(db_column='SubmodelID', primary_key=True)
    sub_model_name = models.CharField(max_length=50, db_column='SubModelName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')
    sub_model_id = models.IntegerField(db_column='SubModelID')

    class Meta:
        db_table = "autocare_vcdb.sub_model"
        managed = True

class Transmission(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    transmission_id = models.IntegerField(db_column='TransmissionID', primary_key=True)
    transmission_base = models.ForeignKey("TransmissionBase", db_column="TransmissionBaseID", on_delete=models.DO_NOTHING, related_name="+")
    transmission_mfr_code = models.ForeignKey("TransmissionMfrCode", db_column="TransmissionMfrCodeID", on_delete=models.DO_NOTHING, related_name="+")
    transmission_elec_controlled = models.ForeignKey("ElecControlled", db_column="TransmissionElecControlledID", on_delete=models.DO_NOTHING, related_name="+")
    transmission_mfr = models.ForeignKey("Mfr", db_column="TransmissionMfrID", on_delete=models.DO_NOTHING, related_name="+")
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.transmission"
        managed = True

class TransmissionBase(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    transmission_base_id = models.IntegerField(db_column='TransmissionBaseID', primary_key=True)
    transmission_type = models.ForeignKey("TransmissionType", db_column="TransmissionTypeID", on_delete=models.DO_NOTHING, related_name="+")
    transmission_num_speeds = models.ForeignKey("TransmissionNumSpeeds", db_column="TransmissionNumSpeedsID", on_delete=models.DO_NOTHING, related_name="+")
    transmission_control_type = models.ForeignKey("TransmissionControlType", db_column="TransmissionControlTypeID", on_delete=models.DO_NOTHING, related_name="+")
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.transmission_base"
        managed = True

class TransmissionControlType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    transmission_control_type_id = models.IntegerField(db_column='TransmissionControlTypeID', primary_key=True)
    transmission_control_type_name = models.CharField(max_length=30, db_column='TransmissionControlTypeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.transmission_control_type"
        managed = True

class TransmissionMfrCode(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    transmission_mfr_code_id = models.IntegerField(db_column='TransmissionMfrCodeID', primary_key=True)
    transmission_mfr_code = models.CharField(max_length=30, db_column='TransmissionMfrCode')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.transmission_mfr_code"
        managed = True

class TransmissionNumSpeeds(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    transmission_num_speeds_id = models.IntegerField(db_column='TransmissionNumSpeedsID', primary_key=True)
    transmission_num_speeds = models.CharField(max_length=3, db_column='TransmissionNumSpeeds')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.transmission_num_speeds"
        managed = True

class TransmissionType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    transmission_type_id = models.IntegerField(db_column='TransmissionTypeID', primary_key=True)
    transmission_type_name = models.CharField(max_length=30, db_column='TransmissionTypeName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.DateTimeField(null=True, blank=True, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.transmission_type"
        managed = True

class Valves(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    valves_id = models.IntegerField(db_column='ValvesID', primary_key=True)
    valves_per_engine = models.CharField(max_length=3, db_column='ValvesPerEngine')

    class Meta:
        db_table = "autocare_vcdb.valves"
        managed = True

class Vehicle(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_id = models.IntegerField(db_column='VehicleID', primary_key=True)
    base_vehicle = models.ForeignKey("BaseVehicle", db_column="BaseVehicleID", on_delete=models.DO_NOTHING, related_name="+")
    submodel = models.ForeignKey("SubModel", db_column="SubmodelID", on_delete=models.DO_NOTHING, related_name="+")
    region = models.ForeignKey("Region", db_column="RegionID", on_delete=models.DO_NOTHING, related_name="+")
    source = models.CharField(null=True, blank=True, max_length=10, db_column='Source')
    publication_stage = models.ForeignKey("PublicationStage", db_column="PublicationStageID", on_delete=models.DO_NOTHING, related_name="+")
    publication_stage_source = models.CharField(max_length=100, db_column='PublicationStageSource')
    publication_stage_date = models.DateTimeField(db_column='PublicationStageDate')
    sub_model_id = models.IntegerField(db_column='SubModelID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.vehicle"
        managed = True

class VehicleToBedConfig(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_to_bed_config_id = models.IntegerField(db_column='VehicleToBedConfigID', primary_key=True)
    vehicle = models.ForeignKey("Vehicle", db_column="VehicleID", on_delete=models.DO_NOTHING, related_name="+")
    bed_config = models.ForeignKey("BedConfig", db_column="BedConfigID", on_delete=models.DO_NOTHING, related_name="+")
    source = models.CharField(null=True, blank=True, max_length=10, db_column='Source')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.vehicle_to_bed_config"
        managed = True

class VehicleToBodyConfig(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_to_body_config_id = models.IntegerField(db_column='VehicleToBodyConfigID', primary_key=True)
    vehicle = models.ForeignKey("Vehicle", db_column="VehicleID", on_delete=models.DO_NOTHING, related_name="+")
    wheel_base = models.ForeignKey("WheelBase", db_column="WheelBaseID", on_delete=models.DO_NOTHING, related_name="+")
    bed_config = models.ForeignKey("BedConfig", db_column="BedConfigID", on_delete=models.DO_NOTHING, related_name="+")
    body_style_config = models.ForeignKey("BodyStyleConfig", db_column="BodyStyleConfigID", on_delete=models.DO_NOTHING, related_name="+")
    mfr_body_code = models.ForeignKey("MfrBodyCode", db_column="MfrBodyCodeID", on_delete=models.DO_NOTHING, related_name="+")
    source = models.CharField(null=True, blank=True, max_length=10, db_column='Source')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.vehicle_to_body_config"
        managed = True

class VehicleToBodyStyleConfig(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_to_body_style_config_id = models.IntegerField(db_column='VehicleToBodyStyleConfigID', primary_key=True)
    vehicle = models.ForeignKey("Vehicle", db_column="VehicleID", on_delete=models.DO_NOTHING, related_name="+")
    body_style_config = models.ForeignKey("BodyStyleConfig", db_column="BodyStyleConfigID", on_delete=models.DO_NOTHING, related_name="+")
    source = models.CharField(null=True, blank=True, max_length=10, db_column='Source')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.vehicle_to_body_style_config"
        managed = True

class VehicleToBrakeConfig(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_to_brake_config_id = models.IntegerField(db_column='VehicleToBrakeConfigID', primary_key=True)
    vehicle = models.ForeignKey("Vehicle", db_column="VehicleID", on_delete=models.DO_NOTHING, related_name="+")
    brake_config = models.ForeignKey("BrakeConfig", db_column="BrakeConfigID", on_delete=models.DO_NOTHING, related_name="+")
    source = models.CharField(null=True, blank=True, max_length=10, db_column='Source')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.vehicle_to_brake_config"
        managed = True

class VehicleToClass(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_to_class_id = models.IntegerField(db_column='VehicleToClassID', primary_key=True)
    vehicle = models.ForeignKey("Vehicle", db_column="VehicleID", on_delete=models.DO_NOTHING, related_name="+")
    class_ = models.ForeignKey("ClassModel", db_column="ClassID", on_delete=models.DO_NOTHING, related_name="+")
    source = models.CharField(null=True, blank=True, max_length=10, db_column='Source')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.vehicle_to_class"
        managed = True

class VehicleToDriveType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_to_drive_type_id = models.IntegerField(db_column='VehicleToDriveTypeID', primary_key=True)
    vehicle = models.ForeignKey("Vehicle", db_column="VehicleID", on_delete=models.DO_NOTHING, related_name="+")
    drive_type = models.ForeignKey("DriveType", db_column="DriveTypeID", on_delete=models.DO_NOTHING, related_name="+")
    source = models.CharField(null=True, blank=True, max_length=10, db_column='Source')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.vehicle_to_drive_type"
        managed = True

class VehicleToEngineConfig(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_to_engine_config_id = models.IntegerField(db_column='VehicleToEngineConfigID', primary_key=True)
    vehicle = models.ForeignKey("Vehicle", db_column="VehicleID", on_delete=models.DO_NOTHING, related_name="+")
    engine_config = models.ForeignKey("EngineConfig2", db_column="EngineConfigID", on_delete=models.DO_NOTHING, related_name="+")
    source = models.CharField(null=True, blank=True, max_length=10, db_column='Source')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.vehicle_to_engine_config"
        managed = True

class VehicleToMfrBodyCode(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_to_mfr_body_code_id = models.IntegerField(db_column='VehicleToMfrBodyCodeID', primary_key=True)
    vehicle = models.ForeignKey("Vehicle", db_column="VehicleID", on_delete=models.DO_NOTHING, related_name="+")
    mfr_body_code = models.ForeignKey("MfrBodyCode", db_column="MfrBodyCodeID", on_delete=models.DO_NOTHING, related_name="+")
    source = models.CharField(null=True, blank=True, max_length=10, db_column='Source')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.vehicle_to_mfr_body_code"
        managed = True

class VehicleToSpringTypeConfig(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_to_spring_type_config_id = models.IntegerField(db_column='VehicleToSpringTypeConfigID', primary_key=True)
    vehicle = models.ForeignKey("Vehicle", db_column="VehicleID", on_delete=models.DO_NOTHING, related_name="+")
    spring_type_config = models.ForeignKey("SpringTypeConfig", db_column="SpringTypeConfigID", on_delete=models.DO_NOTHING, related_name="+")
    source = models.CharField(max_length=10, null=True, blank=True, db_column='Source')

    class Meta:
        db_table = "autocare_vcdb.vehicle_to_spring_type_config"
        managed = True

class VehicleToSteeringConfig(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_to_steering_config_id = models.IntegerField(db_column='VehicleToSteeringConfigID', primary_key=True)
    vehicle = models.ForeignKey("Vehicle", db_column="VehicleID", on_delete=models.DO_NOTHING, related_name="+")
    steering_config = models.ForeignKey("SteeringConfig", db_column="SteeringConfigID", on_delete=models.DO_NOTHING, related_name="+")
    source = models.CharField(null=True, blank=True, max_length=10, db_column='Source')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.vehicle_to_steering_config"
        managed = True

class VehicleToTransmission(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_to_transmission_id = models.IntegerField(db_column='VehicleToTransmissionID', primary_key=True)
    vehicle = models.ForeignKey("Vehicle", db_column="VehicleID", on_delete=models.DO_NOTHING, related_name="+")
    transmission = models.ForeignKey("Transmission", db_column="TransmissionID", on_delete=models.DO_NOTHING, related_name="+")
    source = models.CharField(null=True, blank=True, max_length=10, db_column='Source')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.vehicle_to_transmission"
        managed = True

class VehicleToWheelBase(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_to_wheel_base_id = models.IntegerField(db_column='VehicleToWheelBaseID', primary_key=True)
    vehicle = models.ForeignKey("Vehicle", db_column="VehicleID", on_delete=models.DO_NOTHING, related_name="+")
    wheel_base_id = models.IntegerField(db_column='WheelBaseID')
    source = models.CharField(null=True, blank=True, max_length=10, db_column='Source')
    vehicle_to_wheelbase_id = models.IntegerField(db_column='VehicleToWheelbaseID')
    wheelbase_id = models.IntegerField(db_column='WheelbaseID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.vehicle_to_wheel_base"
        managed = True

class VehicleType(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_type_id = models.IntegerField(db_column='VehicleTypeID', primary_key=True)
    vehicle_type_name = models.CharField(max_length=50, db_column='VehicleTypeName')
    vehicle_type_group_id = models.IntegerField(null=True, blank=True, db_column='VehicleTypeGroupID')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.vehicle_type"
        managed = True

class VehicleTypeGroup(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    vehicle_type_group_id = models.IntegerField(db_column='VehicleTypeGroupID')
    vehicle_type_group_name = models.CharField(max_length=50, db_column='VehicleTypeGroupName')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.vehicle_type_group"
        managed = True

class WheelBase(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    wheel_base_id = models.IntegerField(db_column='WheelBaseID', primary_key=True)
    wheel_base = models.CharField(max_length=10, db_column='WheelBase')
    wheel_base_metric = models.CharField(max_length=10, db_column='WheelBaseMetric')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')
    source = models.CharField(null=True, blank=True, max_length=255, db_column='Source')
    culture_id = models.CharField(null=True, blank=True, max_length=255, db_column='CultureID')
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')

    class Meta:
        db_table = "autocare_vcdb.wheel_base"
        managed = True

class Year(models.Model):
    """AUTO-GENERATED — READY FOR API INGEST"""

    year_id = models.IntegerField(db_column='YearID', primary_key=True)
    effective_date_time = models.DateTimeField(db_column='EffectiveDateTime')
    end_date_time = models.CharField(null=True, blank=True, max_length=255, db_column='EndDateTime')

    class Meta:
        db_table = "autocare_vcdb.year"
        managed = True

# ---- Many-to-Many wiring (through join tables) ----
# VehicleToBrakeConfig => M2M BrakeConfig <-> Vehicle through VehicleToBrakeConfig
setattr(BrakeConfig, 'vehicles', models.ManyToManyField('Vehicle', through='VehicleToBrakeConfig', related_name='+'))
setattr(Vehicle, 'brake_configs', models.ManyToManyField('BrakeConfig', through='VehicleToBrakeConfig', related_name='+'))

# EngineBase2 => M2M EngineBlock <-> EngineBoreStroke through EngineBase2
setattr(EngineBlock, 'engine_bore_strokes', models.ManyToManyField('EngineBoreStroke', through='EngineBase2', related_name='+'))
setattr(EngineBoreStroke, 'engine_blocks', models.ManyToManyField('EngineBlock', through='EngineBase2', related_name='+'))

# VehicleToBedConfig => M2M BedConfig <-> Vehicle through VehicleToBedConfig
setattr(BedConfig, 'vehicles', models.ManyToManyField('Vehicle', through='VehicleToBedConfig', related_name='+'))
setattr(Vehicle, 'bed_configs', models.ManyToManyField('BedConfig', through='VehicleToBedConfig', related_name='+'))

# VehicleToBodyStyleConfig => M2M BodyStyleConfig <-> Vehicle through VehicleToBodyStyleConfig
setattr(BodyStyleConfig, 'vehicles', models.ManyToManyField('Vehicle', through='VehicleToBodyStyleConfig', related_name='+'))
setattr(Vehicle, 'body_style_configs', models.ManyToManyField('BodyStyleConfig', through='VehicleToBodyStyleConfig', related_name='+'))

# VehicleToDriveType => M2M DriveType <-> Vehicle through VehicleToDriveType
setattr(DriveType, 'vehicles', models.ManyToManyField('Vehicle', through='VehicleToDriveType', related_name='+'))
setattr(Vehicle, 'drive_types', models.ManyToManyField('DriveType', through='VehicleToDriveType', related_name='+'))

# VehicleToEngineConfig => M2M EngineConfig2 <-> Vehicle through VehicleToEngineConfig
setattr(EngineConfig2, 'vehicles', models.ManyToManyField('Vehicle', through='VehicleToEngineConfig', related_name='+'))
setattr(Vehicle, 'engine_config_2s', models.ManyToManyField('EngineConfig2', through='VehicleToEngineConfig', related_name='+'))

# VehicleToMfrBodyCode => M2M MfrBodyCode <-> Vehicle through VehicleToMfrBodyCode
setattr(MfrBodyCode, 'vehicles', models.ManyToManyField('Vehicle', through='VehicleToMfrBodyCode', related_name='+'))
setattr(Vehicle, 'mfr_body_codes', models.ManyToManyField('MfrBodyCode', through='VehicleToMfrBodyCode', related_name='+'))

# VehicleToSpringTypeConfig => M2M SpringTypeConfig <-> Vehicle through VehicleToSpringTypeConfig
setattr(SpringTypeConfig, 'vehicles', models.ManyToManyField('Vehicle', through='VehicleToSpringTypeConfig', related_name='+'))
setattr(Vehicle, 'spring_type_configs', models.ManyToManyField('SpringTypeConfig', through='VehicleToSpringTypeConfig', related_name='+'))

# VehicleToSteeringConfig => M2M SteeringConfig <-> Vehicle through VehicleToSteeringConfig
setattr(SteeringConfig, 'vehicles', models.ManyToManyField('Vehicle', through='VehicleToSteeringConfig', related_name='+'))
setattr(Vehicle, 'steering_configs', models.ManyToManyField('SteeringConfig', through='VehicleToSteeringConfig', related_name='+'))

# VehicleToTransmission => M2M Transmission <-> Vehicle through VehicleToTransmission
setattr(Transmission, 'vehicles', models.ManyToManyField('Vehicle', through='VehicleToTransmission', related_name='+'))
setattr(Vehicle, 'transmissions', models.ManyToManyField('Transmission', through='VehicleToTransmission', related_name='+'))

# VehicleToClass => M2M ClassModel <-> Vehicle through VehicleToClass
setattr(ClassModel, 'vehicles', models.ManyToManyField('Vehicle', through='VehicleToClass', related_name='+'))
setattr(Vehicle, 'class_s', models.ManyToManyField('ClassModel', through='VehicleToClass', related_name='+'))
