# Generated by Django 5.2.9 on 2025-12-29 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PartTypeStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "style_id",
                    models.IntegerField(blank=True, db_column="StyleID", null=True),
                ),
                (
                    "part_terminology_id",
                    models.IntegerField(
                        blank=True, db_column="PartTerminologyID", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "PartTypeStyle",
                "verbose_name_plural": "PartTypeStyles",
                "db_table": '"autocare_padb"."PartTypeStyle"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "style_id",
                    models.IntegerField(blank=True, db_column="StyleID", null=True),
                ),
                (
                    "style_name",
                    models.CharField(
                        blank=True, db_column="StyleName", max_length=225, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Style",
                "verbose_name_plural": "Styles",
                "db_table": '"autocare_padb"."Style"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "padb_version",
                    models.CharField(
                        blank=True, db_column="PAdbVersion", max_length=10, null=True
                    ),
                ),
                (
                    "padb_publication",
                    models.DateField(
                        blank=True, db_column="PAdbPublication", null=True
                    ),
                ),
                (
                    "pcdb_publication",
                    models.DateField(
                        blank=True, db_column="PCdbPublication", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Version",
                "verbose_name_plural": "Versions",
                "db_table": '"autocare_padb"."Version"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MeasurementGroup",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "measurement_group_id",
                    models.IntegerField(
                        db_column="MeasurementGroupID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "measurement_group_name",
                    models.CharField(
                        blank=True,
                        db_column="MeasurementGroupName",
                        max_length=80,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "MeasurementGroup",
                "verbose_name_plural": "MeasurementGroups",
                "db_table": '"autocare_padb"."MeasurementGroup"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["measurement_group_id"],
                        name="Measurement_Measure_81df8a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MetaData",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "meta_id",
                    models.IntegerField(
                        db_column="MetaID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "meta_name",
                    models.CharField(
                        blank=True, db_column="MetaName", max_length=80, null=True
                    ),
                ),
                (
                    "meta_descr",
                    models.CharField(
                        blank=True, db_column="MetaDescr", max_length=512, null=True
                    ),
                ),
                (
                    "meta_format",
                    models.CharField(
                        blank=True, db_column="MetaFormat", max_length=10, null=True
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        blank=True, db_column="DataType", max_length=50, null=True
                    ),
                ),
                (
                    "min_length",
                    models.IntegerField(blank=True, db_column="MinLength", null=True),
                ),
                (
                    "max_length",
                    models.IntegerField(blank=True, db_column="MaxLength", null=True),
                ),
            ],
            options={
                "verbose_name": "MetaData",
                "verbose_name_plural": "MetaDatas",
                "db_table": '"autocare_padb"."MetaData"',
                "managed": True,
                "indexes": [
                    models.Index(fields=["meta_id"], name="MetaData_MetaID_9374e7_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="MetaUOMCodes",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "meta_uomid",
                    models.IntegerField(
                        db_column="MetaUOMID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "uom_code",
                    models.CharField(
                        blank=True, db_column="UOMCode", max_length=10, null=True
                    ),
                ),
                (
                    "uom_description",
                    models.CharField(
                        blank=True,
                        db_column="UOMDescription",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "uom_label",
                    models.CharField(
                        blank=True, db_column="UOMLabel", max_length=10, null=True
                    ),
                ),
                (
                    "measurement_group",
                    models.ForeignKey(
                        db_column="MeasurementGroupID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_padb.measurementgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "MetaUOMCodes",
                "verbose_name_plural": "MetaUOMCodess",
                "db_table": '"autocare_padb"."MetaUOMCodes"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MetaUOMCodeAssignment",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "meta_uom_code_assignment_id",
                    models.IntegerField(
                        db_column="MetaUOMCodeAssignmentID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("paptid", models.IntegerField(db_column="PAPTID")),
                (
                    "meta_uomid",
                    models.ForeignKey(
                        db_column="MetaUOMID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_padb.metauomcodes",
                    ),
                ),
            ],
            options={
                "verbose_name": "MetaUOMCodeAssignment",
                "verbose_name_plural": "MetaUOMCodeAssignments",
                "db_table": '"autocare_padb"."MetaUOMCodeAssignment"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PartAttributes",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "paid",
                    models.IntegerField(
                        db_column="PAID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "pa_name",
                    models.CharField(
                        blank=True, db_column="PAName", max_length=80, null=True
                    ),
                ),
                (
                    "pa_descr",
                    models.CharField(
                        blank=True, db_column="PADescr", max_length=512, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "PartAttributes",
                "verbose_name_plural": "PartAttributess",
                "db_table": '"autocare_padb"."PartAttributes"',
                "managed": True,
                "indexes": [
                    models.Index(fields=["paid"], name="PartAttribu_PAID_cd1ecd_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PartAttributeAssignment",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "paptid",
                    models.IntegerField(
                        db_column="PAPTID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "part_terminology_id",
                    models.IntegerField(db_column="PartTerminologyID"),
                ),
                (
                    "meta",
                    models.ForeignKey(
                        db_column="MetaID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_padb.metadata",
                    ),
                ),
                (
                    "paid",
                    models.ForeignKey(
                        db_column="PAID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_padb.partattributes",
                    ),
                ),
            ],
            options={
                "verbose_name": "PartAttributeAssignment",
                "verbose_name_plural": "PartAttributeAssignments",
                "db_table": '"autocare_padb"."PartAttributeAssignment"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PartAttributeStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "style_id",
                    models.IntegerField(blank=True, db_column="StyleID", null=True),
                ),
                (
                    "paptid",
                    models.ForeignKey(
                        db_column="PAPTID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_padb.partattributeassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "PartAttributeStyle",
                "verbose_name_plural": "PartAttributeStyles",
                "db_table": '"autocare_padb"."PartAttributeStyle"',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ValidValues",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "valid_value_id",
                    models.IntegerField(
                        db_column="ValidValueID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "valid_value",
                    models.CharField(db_column="ValidValue", max_length=100),
                ),
            ],
            options={
                "verbose_name": "ValidValues",
                "verbose_name_plural": "ValidValuess",
                "db_table": '"autocare_padb"."ValidValues"',
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["valid_value_id"], name="ValidValues_ValidVa_a7adc8_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ValidValueAssignment",
            fields=[
                (
                    "culture_id",
                    models.CharField(
                        blank=True,
                        help_text="CultureID from Autocare API (e.g. en-US).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "effective_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EffectiveDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="EndDateTime from Autocare API (ISO-8601).",
                        null=True,
                    ),
                ),
                (
                    "valid_value_assignment_id",
                    models.IntegerField(
                        db_column="ValidValueAssignmentID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("paptid", models.IntegerField(db_column="PAPTID")),
                (
                    "valid_value",
                    models.ForeignKey(
                        db_column="ValidValueID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autocare_padb.validvalues",
                    ),
                ),
            ],
            options={
                "verbose_name": "ValidValueAssignment",
                "verbose_name_plural": "ValidValueAssignments",
                "db_table": '"autocare_padb"."ValidValueAssignment"',
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="metauomcodes",
            index=models.Index(
                fields=["meta_uomid"], name="MetaUOMCode_MetaUOM_e1bbb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metauomcodeassignment",
            index=models.Index(
                fields=["meta_uom_code_assignment_id"],
                name="MetaUOMCode_MetaUOM_7982f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partattributeassignment",
            index=models.Index(fields=["paptid"], name="PartAttribu_PAPTID_7fa38b_idx"),
        ),
        migrations.AddIndex(
            model_name="validvalueassignment",
            index=models.Index(
                fields=["valid_value_assignment_id"],
                name="ValidValueA_ValidVa_ac71de_idx",
            ),
        ),
    ]
